extern int s1,s2;
extern void generate_gaus_kernal(double *kern,int num,double b);
extern void generate_decay_curve(double *kern,int num,double a,double b,double c);
extern long get_mem(unsigned long size);
extern void free_mem(void *p);
extern double *get_array(int size);
extern long *get_l_array(int size);
extern void convolve(double *in,double *out,double *kern,int s1,int s2);
extern void error(char *c);
extern void print_array(double *f,int n);
extern double convert_from_space(double *map,int num_l);
extern void convert_to_space(double *map,int num_l,double value,double max_map);
extern void add_to_space(double *map,int num_l,double value,double max_map);
extern int fround(double f);
extern double ran0();
extern double ran1(int *idum);
extern double gasdev(int *idum);
extern long int rand1(long int min,long int max);
extern int decimal_date2(char *date,double *d_date);
extern void report_error(int *num_correct,int *num_in_test,int num_types);
extern double erms(double *output,double *desired,int num_pat);
extern void scramble(int *array,int num);
extern int num_bits(int n);
extern void four1(double *data,int nn,int isign);
int hasLetters(char *j);
int strcmp2(char *c, char *d);
extern char* sscanf_n(char *c,int start,int n, double *p);
extern char* sscanf_n_i(char *c,int start,int n, int *p);
extern char* sscanf_n_li(char *c,int start,int n, long *p);
long rand1(long min,long max,long *s1);