/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jri.h"

/* Stubs for class NpCtp */

#ifdef IMPLEMENT_NpCtp
#define _implementing_NpCtp
#endif /* IMPLEMENT_NpCtp */
#define IMPLEMENT_NpCtp
#include "NpCtp.h"

#ifndef UNUSED_NpCtp_GetCommand
JRIMethodID FAR methodID_NpCtp_GetCommand = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
NpCtp_GetCommand(JRIEnv* env, struct NpCtp* self, struct java_lang_String *a) {
	if (methodID_NpCtp_GetCommand == JRIUninitialized) {
		assert(!"Forgot to call use_NpCtp(env) before calling method GetCommand (Ljava/lang/String;)I");
	}
	return (jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, self, methodID_NpCtp_GetCommand, a);
}
#endif /* DEBUG */
#endif /* UNUSED_NpCtp_GetCommand */

#ifndef UNUSED_NpCtp_FileDownload
JRIMethodID FAR methodID_NpCtp_FileDownload = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
NpCtp_FileDownload(JRIEnv* env, struct NpCtp* self, struct java_lang_String *a) {
	if (methodID_NpCtp_FileDownload == JRIUninitialized) {
		assert(!"Forgot to call use_NpCtp(env) before calling method FileDownload (Ljava/lang/String;)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_NpCtp_FileDownload, a);
}
#endif /* DEBUG */
#endif /* UNUSED_NpCtp_FileDownload */

#ifndef UNUSED_NpCtp_PutSrc
JRIMethodID FAR methodID_NpCtp_PutSrc = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
NpCtp_PutSrc(JRIEnv* env, struct NpCtp* self, struct java_lang_String *a) {
	if (methodID_NpCtp_PutSrc == JRIUninitialized) {
		assert(!"Forgot to call use_NpCtp(env) before calling method PutSrc (Ljava/lang/String;)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_NpCtp_PutSrc, a);
}
#endif /* DEBUG */
#endif /* UNUSED_NpCtp_PutSrc */

#ifndef UNUSED_NpCtp_GetSrc
JRIMethodID FAR methodID_NpCtp_GetSrc = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String *)
NpCtp_GetSrc(JRIEnv* env, struct NpCtp* self) {
	if (methodID_NpCtp_GetSrc == JRIUninitialized) {
		assert(!"Forgot to call use_NpCtp(env) before calling method GetSrc ()Ljava/lang/String;");
	}
	return (struct java_lang_String *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_NpCtp_GetSrc);
}
#endif /* DEBUG */
#endif /* UNUSED_NpCtp_GetSrc */

#ifndef UNUSED_NpCtp_new
JRIMethodID FAR methodID_NpCtp_new = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct NpCtp*)
NpCtp_new(JRIEnv* env, struct java_lang_Class* clazz) {
	if (methodID_NpCtp_new == JRIUninitialized) {
		assert(!"Forgot to call use_NpCtp(env) before calling method <init> ()V");
	}
	return (struct NpCtp*)JRI_NewObject(env)(env, JRI_NewObject_op, clazz, methodID_NpCtp_new);
}
#endif /* DEBUG */
#endif /* UNUSED_NpCtp_new */

#ifndef UNUSED_NpCtp_PutContext
JRIMethodID FAR methodID_NpCtp_PutContext = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(void)
NpCtp_PutContext(JRIEnv* env, struct NpCtp* self, struct java_lang_String *a) {
	if (methodID_NpCtp_PutContext == JRIUninitialized) {
		assert(!"Forgot to call use_NpCtp(env) before calling method PutContext (Ljava/lang/String;)V");
	}
	(void)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_NpCtp_PutContext, a);
}
#endif /* DEBUG */
#endif /* UNUSED_NpCtp_PutContext */

#ifndef UNUSED_NpCtp_GetContext
JRIMethodID FAR methodID_NpCtp_GetContext = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(struct java_lang_String *)
NpCtp_GetContext(JRIEnv* env, struct NpCtp* self) {
	if (methodID_NpCtp_GetContext == JRIUninitialized) {
		assert(!"Forgot to call use_NpCtp(env) before calling method GetContext ()Ljava/lang/String;");
	}
	return (struct java_lang_String *)JRI_CallMethod(env)(env, JRI_CallMethod_op, self, methodID_NpCtp_GetContext);
}
#endif /* DEBUG */
#endif /* UNUSED_NpCtp_GetContext */

#ifndef UNUSED_NpCtp_DoCommand
JRIMethodID FAR methodID_NpCtp_DoCommand = JRIUninitialized;
#ifdef DEBUG
JRI_PUBLIC_API(jint)
NpCtp_DoCommand(JRIEnv* env, struct NpCtp* self, struct java_lang_String *a) {
	if (methodID_NpCtp_DoCommand == JRIUninitialized) {
		assert(!"Forgot to call use_NpCtp(env) before calling method DoCommand (Ljava/lang/String;)I");
	}
	return (jint)JRI_CallMethodInt(env)(env, JRI_CallMethod_op, self, methodID_NpCtp_DoCommand, a);
}
#endif /* DEBUG */
#endif /* UNUSED_NpCtp_DoCommand */

#ifndef UNUSED_use_NpCtp

static jglobal _globalclass_NpCtp = NULL;

JRI_PUBLIC_API(struct java_lang_Class*)
use_NpCtp(JRIEnv* env)
{
	if (_globalclass_NpCtp == NULL) {
		struct java_lang_Class* clazz = JRI_FindClass(env, classname_NpCtp);
		if (clazz == NULL) {
			JRI_ThrowNew(env, JRI_FindClass(env, "java/lang/ClassNotFoundException"), classname_NpCtp);
			return NULL;
		}
		use_NpCtp_GetCommand(env, clazz);
		use_NpCtp_FileDownload(env, clazz);
		use_NpCtp_PutSrc(env, clazz);
		use_NpCtp_GetSrc(env, clazz);
		use_NpCtp_new(env, clazz);
		use_NpCtp_PutContext(env, clazz);
		use_NpCtp_GetContext(env, clazz);
		use_NpCtp_DoCommand(env, clazz);
		_globalclass_NpCtp = JRI_NewGlobalRef(env, clazz);
		return clazz;
	}
	else {
		return (struct java_lang_Class*)JRI_GetGlobalRef(env, _globalclass_NpCtp);
	}
}

JRI_PUBLIC_API(void)
unuse_NpCtp(JRIEnv* env)
{
	if (_globalclass_NpCtp != NULL) {
		struct java_lang_Class* clazz = (struct java_lang_Class*)JRI_GetGlobalRef(env, _globalclass_NpCtp);
		unuse_NpCtp_GetCommand(env, clazz);
		unuse_NpCtp_FileDownload(env, clazz);
		unuse_NpCtp_PutSrc(env, clazz);
		unuse_NpCtp_GetSrc(env, clazz);
		unuse_NpCtp_new(env, clazz);
		unuse_NpCtp_PutContext(env, clazz);
		unuse_NpCtp_GetContext(env, clazz);
		unuse_NpCtp_DoCommand(env, clazz);
		JRI_DisposeGlobalRef(env, _globalclass_NpCtp);
		_globalclass_NpCtp = NULL;
		clazz = NULL;	/* prevent unused variable 'clazz' warning */
	}
}

#endif /* UNUSED_use_NpCtp */

#ifdef _implementing_NpCtp

JRI_PUBLIC_API(struct java_lang_Class*)
register_NpCtp(JRIEnv* env)
{
	char* nativeNamesAndSigs[] = {
		"GetCommand(Ljava/lang/String;)I",
		"FileDownload(Ljava/lang/String;)V",
		"PutSrc(Ljava/lang/String;)V",
		"GetSrc()Ljava/lang/String;",
		"PutContext(Ljava/lang/String;)V",
		"GetContext()Ljava/lang/String;",
		"DoCommand(Ljava/lang/String;)I",
		NULL
	};
	void* nativeProcs[] = {
		(void*)native_NpCtp_GetCommand,
		(void*)native_NpCtp_FileDownload,
		(void*)native_NpCtp_PutSrc,
		(void*)native_NpCtp_GetSrc,
		(void*)native_NpCtp_PutContext,
		(void*)native_NpCtp_GetContext,
		(void*)native_NpCtp_DoCommand,
		NULL
	};
	struct java_lang_Class* clazz = JRI_FindClass(env, classname_NpCtp);
	if (clazz == NULL) {
		JRI_ThrowNew(env, JRI_FindClass(env, "java/lang/ClassNotFoundException"), classname_NpCtp);
		return NULL;
	}
	JRI_RegisterNatives(env, clazz, nativeNamesAndSigs, nativeProcs);
	use_NpCtp(env);
	return clazz;
}

JRI_PUBLIC_API(void)
unregister_NpCtp(JRIEnv* env)
{
	struct java_lang_Class* clazz = JRI_FindClass(env, classname_NpCtp);
	JRI_UnregisterNatives(env, clazz);
	unuse_NpCtp(env);
}

#endif /* _implementing_NpCtp */

/* These stub routines are generated for compatibility with the JDK: */

#ifndef NO_JDK

/* SYMBOL: "NpCtp/GetCommand(Ljava/lang/String;)I", Java_NpCtp_GetCommand_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_NpCtp_GetCommand_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].i = native_NpCtp_GetCommand(_EE_,_P_[0].p,((_P_[1].p)));
	return _P_ + 1;
}

/* SYMBOL: "NpCtp/FileDownload(Ljava/lang/String;)V", Java_NpCtp_FileDownload_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_NpCtp_FileDownload_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_NpCtp_FileDownload(_EE_,_P_[0].p,((_P_[1].p)));
	return _P_;
}

/* SYMBOL: "NpCtp/PutSrc(Ljava/lang/String;)V", Java_NpCtp_PutSrc_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_NpCtp_PutSrc_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_NpCtp_PutSrc(_EE_,_P_[0].p,((_P_[1].p)));
	return _P_;
}

/* SYMBOL: "NpCtp/GetSrc()Ljava/lang/String;", Java_NpCtp_GetSrc_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_NpCtp_GetSrc_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].p = native_NpCtp_GetSrc(_EE_,_P_[0].p);
	return _P_ + 1;
}

/* SYMBOL: "NpCtp/PutContext(Ljava/lang/String;)V", Java_NpCtp_PutContext_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_NpCtp_PutContext_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	(void) native_NpCtp_PutContext(_EE_,_P_[0].p,((_P_[1].p)));
	return _P_;
}

/* SYMBOL: "NpCtp/GetContext()Ljava/lang/String;", Java_NpCtp_GetContext_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_NpCtp_GetContext_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].p = native_NpCtp_GetContext(_EE_,_P_[0].p);
	return _P_ + 1;
}

/* SYMBOL: "NpCtp/DoCommand(Ljava/lang/String;)I", Java_NpCtp_DoCommand_stub */
JRI_PUBLIC_API(JRI_JDK_stack_item*)
Java_NpCtp_DoCommand_stub(JRI_JDK_stack_item* _P_, JRIEnv* _EE_) {
	_P_[0].i = native_NpCtp_DoCommand(_EE_,_P_[0].p,((_P_[1].p)));
	return _P_ + 1;
}

#endif /* NO_JDK */

