/*		   ACK-3D ( Animation Construction Kit 3D )		      */
/* External Reference */
/* Author: Lary Myers */

extern	long	    LastX1;
extern	long	    LastY1;
extern	long	    iLastX;
extern	long	    iLastY;
extern	int	    MaxDistance;
extern	int	    ErrorCode;
extern	int	    xMapPosn;
extern	int	    yMapPosn;
extern	int	    DefZone[];
extern	int	    AckLightZones[];
extern	UCHAR far   *HtTable[];
extern	UINT  far   *Grid;
extern	UINT  far   *ObjGrid;
extern	SPECIALCODE SpecialCodes[];
extern	int	    TotalSpecial;
extern	int	    DistanceTable[];
extern	long  far   *AdjustTable;
extern	WALLARRAY   Walls[];
extern	int	    xSecretmPos;
extern	int	    xSecretmPos1;
extern	int	    xSecretColumn;
extern	int	    ySecretmPos;
extern	int	    ySecretmPos1;
extern	int	    ySecretColumn;
extern	int	    TotalSecret;
extern	int	    ViewColumn;
extern	long far    *SinTable;
extern	long far    *CosTable;
extern	long far    *LongTanTable;
extern	long far    *LongInvTanTable;
extern	long far    *InvCosTable;
extern	long far    *InvSinTable;
extern	long far    *LongCosTable;
extern	long far    *ViewCosTable;
extern	long far    *xNextTable;
extern	long far    *yNextTable;
extern	UCHAR	    ObjFlags[];
extern	int	    TotalObjects;
extern	int	    LastObjectHit;
extern	UCHAR	    ObjNumber[];
extern	int	    ObjMapPosn[];
extern	long	    ObjRelDist[];
extern	int	    DirDx[];
extern	int	    DirDy[];
extern	int	    DirAngle[];
extern	UCHAR	    LightMap[];

