//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by test.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TEST_DIALOG                 102
#define IDR_MAINFRAME                   128
#define IDC_COUNTRY_LIST                1000
#define IDC_REGISTRATION_MODEM          1002
#define IDC_SREGISTRATION_PHONE         1003
#define IDC_REGISTRATION_PHONE          1003
#define IDC_SREGISTRATION_FAX           1004
#define IDC_REGISTRATION_FAX            1004
#define IDC_REGISTRATION_MAIL           1005
#define IDC_REGISTRATION_MODEM2         1006
#define IDC_SALES_MODEM                 1006
#define IDC_SREGISTRATION_PHONE2        1007
#define IDC_SALES_PHONE                 1007
#define IDC_SREGISTRATION_FAX2          1008
#define IDC_SALES_FAX                   1008
#define IDC_REGISTRATION_MAIL2          1009
#define IDC_SALES_MAIL                  1009
#define IDC_IS_US_LOCAL                 1010
#define IDC_WEB_SITE                    1011
#define IDC_REGISTRATION_HELP           1012
#define IDC_SALES_HELP                  1013
#define IDC_COUNTRY                     1014
#define IDC_TAX_RATES                   1015

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1015
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
