

#ifndef _BUTTONBMPS_H_
#define _BUTTONBMPS_H_

#define IDB_STYLE_BOLD_BTN											22000
#define IDB_STYLE_ITALIC_BTN										22001
#define IDB_STYLE_UNDERLINE_BTN									22002
#define IDB_NO_PREVIEW												22003
#define IDB_PAPERTYPE_PLAIN										22004
#define IDB_PAPERTYPE_PREPERFED4									22005
#define IDB_PAPERTYPE_PREPERFED2									22006


// Envelope feed position IDs
#define BITMAP_ENVELOPE_QUARTERPAGE								22050
#define BITMAP_ENVELOPE_AEROGRAM									22051
#define BITMAP_ENVELOPE_ARROW										22053
#define BITMAP_ENVELOPE_LFT_FLAP_CTR							22054
#define BITMAP_ENVELOPE_LFT_FLAP_LFT							22055
#define BITMAP_ENVELOPE_LFT_FLAP_RGT							22056
#define BITMAP_ENVELOPE_LFT_STMP_CTR							22057
#define BITMAP_ENVELOPE_LFT_STMP_LFT							22058
#define BITMAP_ENVELOPE_LFT_STMP_RGT       					22059
#define BITMAP_ENVELOPE_RGT_FLAP_CTR       					22060
#define BITMAP_ENVELOPE_RGT_FLAP_LFT       					22061
#define BITMAP_ENVELOPE_RGT_FLAP_RGT       					22062
#define BITMAP_ENVELOPE_RGT_STMP_CTR       					22063
#define BITMAP_ENVELOPE_RGT_STMP_LFT       					22064
#define BITMAP_ENVELOPE_RGT_STMP_RGT       					22065
#define BITMAP_ENVELOPE_TOP_FLAP_CTR							22066
#define BITMAP_ENVELOPE_TOP_FLAP_LFT							22067
#define BITMAP_ENVELOPE_TOP_FLAP_RGT							22068
#define BITMAP_ENVELOPE_TOP_STMP_CTR							22069
#define BITMAP_ENVELOPE_TOP_STMP_LFT							22070
#define BITMAP_ENVELOPE_TOP_STMP_RGT       					22071
#define BITMAP_ENVELOPE_BOTTOM_STMP_RGT       				22072
#define BITMAP_ENVELOPE_BOTTOM_STMP_CTR       				22073
#define BITMAP_ENVELOPE_BOTTOM_STMP_LFT       				22074
#define BITMAP_ENVELOPE_BOTTOM_FLAP_CTR       				22075
#define BITMAP_ENVELOPE_BOTTOM_FLAP_RGT       				22076
#define BITMAP_ENVELOPE_BOTTOM_FLAP_LFT       				22077

#define BITMAP_ROTATED_ENVELOPE_LFT_FLAP_CTR					22100
#define BITMAP_ROTATED_ENVELOPE_LFT_FLAP_LFT					22101
#define BITMAP_ROTATED_ENVELOPE_LFT_FLAP_RGT					22102
#define BITMAP_ROTATED_ENVELOPE_LFT_STMP_CTR					22103
#define BITMAP_ROTATED_ENVELOPE_LFT_STMP_LFT					22104
#define BITMAP_ROTATED_ENVELOPE_LFT_STMP_RGT       		22105
#define BITMAP_ROTATED_ENVELOPE_RGT_FLAP_CTR       		22106
#define BITMAP_ROTATED_ENVELOPE_RGT_FLAP_LFT       		22107
#define BITMAP_ROTATED_ENVELOPE_RGT_FLAP_RGT       		22108
#define BITMAP_ROTATED_ENVELOPE_RGT_STMP_CTR       		22109
#define BITMAP_ROTATED_ENVELOPE_RGT_STMP_LFT       		22110
#define BITMAP_ROTATED_ENVELOPE_RGT_STMP_RGT       		22111
#define BITMAP_ROTATED_ENVELOPE_TOP_FLAP_CTR					22112
#define BITMAP_ROTATED_ENVELOPE_TOP_FLAP_LFT					22113
#define BITMAP_ROTATED_ENVELOPE_TOP_FLAP_RGT					22114
#define BITMAP_ROTATED_ENVELOPE_TOP_STMP_CTR					22115
#define BITMAP_ROTATED_ENVELOPE_TOP_STMP_LFT					22116
#define BITMAP_ROTATED_ENVELOPE_TOP_STMP_RGT       		22117
#define BITMAP_ROTATED_ENVELOPE_BOTTOM_STMP_RGT       	22118
#define BITMAP_ROTATED_ENVELOPE_BOTTOM_STMP_CTR       	22119
#define BITMAP_ROTATED_ENVELOPE_BOTTOM_STMP_LFT       	22120
#define BITMAP_ROTATED_ENVELOPE_BOTTOM_FLAP_CTR       	22121
#define BITMAP_ROTATED_ENVELOPE_BOTTOM_FLAP_RGT       	22122
#define BITMAP_ROTATED_ENVELOPE_BOTTOM_FLAP_LFT       	22123

#define BITMAP_BUTTON_THIN_FRAME                         22150
#define BITMAP_BUTTON_MEDIUM_FRAME                       22151
#define BITMAP_BUTTON_THICK_FRAME                        22152
#define BITMAP_BUTTON_DBL_THIN_FRAME                     22153
#define BITMAP_BUTTON_DBL_MEDIUM_FRAME                   22154
#define BITMAP_BUTTON_DBL_THICK_FRAME                    22155
#define BITMAP_BUTTON_PICTURE_FRAME                      22156
#define BITMAP_BUTTON_ROUND_CORNER_FRAME                 22157
#define BITMAP_BUTTON_DROP_SHADOW_FRAME                  22158
#define BITMAP_NO_FRAME                                  22159
#define BITMAP_SCALE_DOTS											22160
#define BITMAP_BUTTON_BOLD_FONT									22161
#define BITMAP_BUTTON_ITALIC_FONT								22162
#define BITMAP_BUTTON_UNDERLINED_FONT							22163
#define BITMAP_BUTTON_JUSTIFY_LEFT								22164
#define BITMAP_BUTTON_JUSTIFY_CENTER							22165
#define BITMAP_BUTTON_JUSTIFY_RIGHT								22166
#define BITMAP_BUTTON_JUSTIFY_FULL								22167
#define BITMAP_BUTTON_PLACEMENT_TOP								22168
#define BITMAP_BUTTON_PLACEMENT_BOTTOM							22169
#define BITMAP_BUTTON_PLACEMENT_CENTER							22170
#define BITMAP_BUTTON_PLACEMENT_FULL							22171
#define BITMAP_BUTTON_BOLD_FONT_F								22172
#define BITMAP_BUTTON_BOLD_FONT_X								22173
#define BITMAP_BUTTON_ITALIC_FONT_F								22174
#define BITMAP_BUTTON_ITALIC_FONT_X								22175
#define BITMAP_BUTTON_UNDERLINED_FONT_F						22176
#define BITMAP_BUTTON_UNDERLINED_FONT_X						22177
#define BITMAP_BUTTON_COLOR_DIALOG								22178
#define BITMAP_FRONTPANEL_STATUSBAR								22179
#define BITMAP_FRONTPANEL_STATUSBAR_SELECTED					22180
#define BITMAP_FRONTPANEL_STATUSBAR_FOCUS						22181
#define BITMAP_FRONTPANEL_STATUSBAR_DISABLED					22182
#define BITMAP_INSIDEPANEL_STATUSBAR							22183
#define BITMAP_INSIDEPANEL_STATUSBAR_SELECTED				22184
#define BITMAP_INSIDEPANEL_STATUSBAR_FOCUS					22185
#define BITMAP_INSIDEPANEL_STATUSBAR_DISABLED				22186
#define BITMAP_BACKPANEL_STATUSBAR								22187
#define BITMAP_BACKPANEL_STATUSBAR_SELECTED					22188
#define BITMAP_BACKPANEL_STATUSBAR_FOCUS						22189
#define BITMAP_BACKPANEL_STATUSBAR_DISABLED					22190
#define BITMAP_ZOOM_STATUSBAR										22191
#define BITMAP_1SPACE												22192
#define BITMAP_2SPACE												22193
#define BITMAP_3SPACE												22194


#endif // _BUTTONBMPS_H_
