//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PSLaunchDLL.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDS_PROJNAME                    100
#define IDS_ABOUTBOX                    101
#define IDS_SETUP_PAGE                  102
#define IDR_PSLAUNCHDATA                103
#define IDR_PSLAUNCHCTRL                104
#define IDR_MAINFRAME                   128
#define IDB_LOGO                        129
#define IDB_GREETINGCARD_FORMAT         134
#define IDB_GREETING_CARD_METHOD        135
#define IDB_TEXT_GREETINGCARD           135
#define IDB_CARD_SHOP                   137
#define IDS_DIR_QSL                     150
#define IDS_DIR_NEWSLETTER              151
#define IDS_DIR_QSLBROCHURE             152
#define IDS_DIR_QSLREPORT               153
#define IDS_DIR_QSLBOOKLET              154
#define IDS_DIR_QSLLETTER               155
#define IDS_DIR_QSLFLYER                156
#define IDS_CDDIR_QSL                   160
#define IDS_CDDIR_QSLNEWSLETTER         161
#define IDS_CDDIR_QSLBROCHURE           162
#define IDS_CDDIR_QSL_REPORT            163
#define IDS_CDDIR_QSLBOOKLET            164
#define IDS_CDDIR_QSLLETTER             165
#define IDS_CDDIR_QSLFLYERS             166
#define IDC_OPEN                        201
#define IDB_PLACEHOLDER_BUTTON          202
#define IDB_PLACEHOLDER_QSL             203
#define IDB_PLACEHOLDER_SCRATCH         204
#define IDB_PLACEHOLDER_PAPER           205
#define IDC_FORMAT_TALL                 206
#define IDB_PREVIEW_WIDE                206
#define IDC_FORMAT_WIDE                 207
#define IDB_NEWSLETTER_SCRATCH          207
#define IDC_INFO_TEXT                   208
#define IDB_CATEGORY_CARDSHOP           209
#define IDC_WORKSPACE_SPLASH            209
#define IDB_WORKSPACE_SIDE              210
#define IDB_CATEGORY_PHOTO              211
#define IDB_CATEGORY_ALL                212
#define IDB_CATEGORY_CREATIVE           213
#define IDC_PROJECT_WEBSITE             213
#define IDB_WORKSPACE_TOP               214
#define IDB_WORKSPACE_SPLASH            215
#define IDB_CATEGORY_INTERNET           216
#define IDC_STATIC_TOPBAR               216
#define IDB_PROJECT_WEBSITE             217
#define IDC_TEXT_HEADER                 217
#define IDB_CATEGORY_CLASSROOM          218
#define IDC_PROJECT_OPTION1             218
#define IDB_CATEGORY_OPEN               219
#define IDC_PROJECT_OPTION2             219
#define IDB_CATEGORY_WORKPLACE          220
#define IDC_PROJECT_OPTION3             220
#define IDB_PREVIEW_WEBSITE             221
#define IDC_PROJECT_OPTION4             221
#define IDB_PREVIEW_NEWSLETTER          222
#define IDC_PROJECT_OPTION5             222
#define IDC_CALENDAR                    222
#define IDB_CATEGORY_ALL_FOCUS          223
#define IDC_PROJECT_OPTION6             223
#define IDC_CALENDAR_YEARLY             223
#define IDB_CATEGORY_CARDSHOP_FOCUS     224
#define IDC_PROJECT_OPTION7             224
#define IDC_CALENDAR_MONTHLY            224
#define IDB_CATEGORY_PHOTO_FOCUS        225
#define IDC_PROJECT_OPTION8             225
#define IDC_CALENDAR_WEEKLY             225
#define IDB_CATEGORY_CLASSROOM_FOCUS    226
#define IDC_PROJECT_OPTION9             226
#define IDC_CALENDAR_DAILY              226
#define IDB_CATEGORY_CREATIVE_FOCUS     227
#define IDC_PROJECT_OPTION10            227
#define IDB_CATEGORY_WORKPLACE_FOCUS    228
#define IDC_PROJECT_OPTION11            228
#define IDB_CATEGORY_INTERNET_FOCUS     229
#define IDC_PROJECT_OPTION12            229
#define IDB_CATEGORY_OPEN_FOCUS         230
#define IDC_PROJECT_OPTION13            230
#define IDC_PROJECT_OPTION14            231
#define IDB_PROJECT_METHOD              232
#define IDC_PROJECT_OPTION15            232
#define IDB_PROJECT_WORKSPACE           233
#define IDC_PROJECT_OPTION16            233
#define IDC_ENVELOPE_STOCK              233
#define IDB_TEXT_WEBSITE                234
#define IDC_PROJECT_OPTION17            234
#define IDC_ENVELOPE_PS                 234
#define IDB_LIST_GREETINGCARDS          235
#define IDC_PROJECT_OPTION18            235
#define IDC_STATIC_PREVIEW              235
#define IDB_PROJECT_PHOTOQUICKPRINTS    236
#define IDC_PROJECT_OPTION19            236
#define IDB_PROJECT_PHOTOCOLLAGES       237
#define IDC_PROJECT_OPTION20            237
#define IDB_PROJECT_PHOTOPAGES          238
#define IDC_PROJECT_OPTION21            238
#define IDB_PROJECT_PHOTOBALBUMS        239
#define IDB_TEXT_PHOTOPROJECT           240
#define IDB_TEXT_SIGN                   241
#define IDB_PROJECT_BLANKPAGES          242
#define IDB_PREVIEW_LABEL5196           243
#define IDB_PREVIEW_LABEL3261SMALL      244
#define IDB_PREVIEW_LABEL5160           245
#define IDB_PREVIEW_LABEL5161           246
#define IDB_PREVIEW_LABEL5162           247
#define IDB_PREVIEW_LABEL5163           248
#define IDB_PREVIEW_LABEL5164           249
#define IDB_PREVIEW_LABEL3261LARGE      250
#define IDB_TEXT_LABEL                  252
#define IDB_PREVIEW_LABELS              253
#define IDB_CALENDAR_YEARLY             256
#define IDB_CALENDAR_MONTHLY            257
#define IDB_CALENDAR_WEEKLY             258
#define IDB_CALENDAR_DAILY              259
#define IDB_TEXT_CALENDAR               260
#define IDB_PREVIEW_GREETINGCARD        261
#define IDB_PREVIEW_PLACEHOLDER         262
#define IDB_PREVIEW_HALFFOLD_WIDE       263
#define IDB_PREVIEW_HALFFOLD_TALL       264
#define IDB_PREVIEW_TALL                265
#define IDB_TEXT_NEWSLETTER             266
#define IDB_PREVIEW_CALENDAR_YEARLY     267
#define IDB_PREVIEW_CALENDAR_MONTHLY    268
#define IDB_PREVIEW_CALENDAR_WEEKLY     269
#define IDB_PREVIEW_CALENDAR_DAILY      270
#define IDB_ENVELOPE_STOCK              273
#define IDB_TEXT_ENVELOPE               276
#define IDB_LIST_ENVELOPE               277
#define IDB_ENVELOPE_PS                 279
#define IDB_PREVIEW_ENVELOPE_PS         280
#define IDB_PREVIEW_ENVELOPE_9x6        281
#define IDB_PREVIEW_ENVELOPE_BUSINESS   282
#define IDB_PREVIEW_ENVELOPE_NOTECARD   283
#define IDB_PREVIEW_ENVELOPE_6x4p75     284
#define IDC_CARDSHOP                    1000
#define IDS_DOCSETUP_APPEARANCE         1000
#define IDC_PHOTO_PROJECTS              1001
#define IDS_DOCSETUP_MARGINS            1001
#define IDC_CREATIVE_CORNER             1002
#define IDC_PROJECTS_ALL                1003
#define IDD_CATEGORY_CREATIVE           1003
#define IDC_PROJECTS_INTERNET           1004
#define IDC_CATEGORY_CLASSROOM          1005
#define IDC_LIST1                       1005
#define IDC_CATEGORY_WORKPLACE          1006
#define IDC_CATEGORY_OPEN               1007
#define IDC_BACK                        1009
#define IDC_NEXT                        1010
#define IDC_STATIC_WORKAREA             1012
#define IDC_COLUMNS                     1020
#define IDC_COLUMNS_CTRL                1021
#define IDC_PAGES                       1023
#define IDC_PAGES_CTRL                  1024
#define IDC_MASTHEAD                    1025
#define IDC_LINES                       1026
#define IDC_SAMPLEGRAPHICS              1026
#define IDC_PAPER                       1030
#define IDC_ORIENT                      1031
#define IDC_PROJECT_LIST                1032
#define IDC_HEADER                      1032
#define IDC_SAMPLETEXT                  1032
#define IDC_FOOTER                      1033
#define IDC_PREVIEW                     1034
#define IDC_HEADER_START                1038
#define IDC_FOOTER_START                1039
#define IDC_TOPMARGIN                   1041
#define IDC_BOTTOMMARGIN                1042
#define IDC_LEFTMARGIN                  1043
#define IDC_RIGHTMARGIN                 1044
#define IDC_TOPSPIN                     1045
#define IDC_BOTTOMSPIN                  1046
#define IDC_LEFTSPIN                    1047
#define IDC_RIGHTSPIN                   1048
#define IDC_STATIC_UNITS1               1093
#define IDC_STATIC_UNITS2               1094
#define IDC_STATIC_UNITS3               1095
#define IDC_STATIC_UNITS4               1096
#define IDS_APP_START                   1500
#define IDS_APP_PRINTSHOP               1501
#define IDS_APP_PRESSWRITER             1502
#define IDS_APP_WEBSITEDESIGNER         1503
#define IDC_GREETING_CARDS              2000
#define IDS_FORMAT_QUARTERFOLD_TALL     2000
#define IDS_FORMAT_QUARTERFOLD_WIDE     2001
#define IDS_FORMAT_HALFFOLD_TALL        2002
#define IDS_FORMAT_HALFFOLD_WIDE        2003
#define IDS_FORMAT_NOTECARD_TALL        2004
#define IDS_FORMAT_NOTECARD_WIDE        2005
#define IDS_FORMAT_TRIFOLD_TALL         2006
#define IDS_FORMAT_TRIFOLD_WIDE         2007
#define IDS_FORMAT_PHOTOCARD35_TALL     2008
#define IDS_FORMAT_PHOTOCARD35_WIDE     2009
#define IDC_START_SCRATCH               2010
#define IDS_FORMAT_PHOTOCARD46_TALL     2010
#define IDS_FORMAT_PHOTOCARD46_WIDE     2011
#define IDC_START_CUSTOMIZE             2011
#define IDS_FORMAT_MINIFOLDCARDTALL     2012
#define IDS_FORMAT_MINIFOLDCARDWIDE     2013
#define IDS_FORMAT_HALFFOLDEMBOSSEDTALL 2014
#define IDS_FORMAT_HALFFOLDEMBOSSEDWIDE 2015
#define IDS_FORMAT_EMBOSSEDTALL         2016
#define IDS_FORMAT_EMBOSSEDWIDE         2017
#define IDC_ONLINE_GREETINGS            2100
#define IDS_FORMAT_LABEL3261SMALL       2100
#define IDS_FORMAT_LABEL3261LARGE       2101
#define IDS_FORMAT_LABEL5160            2102
#define IDS_FORMAT_LABEL5161            2103
#define IDS_FORMAT_LABEL5162            2104
#define IDS_FORMAT_LABEL5163            2105
#define IDS_FORMAT_LABEL5164            2106
#define IDS_FORMAT_LABEL5196            2107
#define IDS_FORMAT_LABEL5197            2108
#define IDS_FORMAT_LABEL5198            2109
#define IDS_FORMAT_LABEL5199FACE        2110
#define IDS_FORMAT_LABEL5199SPINE       2111
#define IDS_FORMAT_LABEL5267            2112
#define IDS_FORMAT_LABEL5385            2113
#define IDS_FORMAT_LABEL5386            2114
#define IDS_FORMAT_LABEL5824            2115
#define IDS_FORMAT_LABELC2160           2116
#define IDS_FORMAT_LABELC2163           2117
#define IDS_FORMAT_LABELC2180           2118
#define IDS_FORMAT_LABELC2166           2119
#define IDS_FORMAT_LABELC2241           2120
#define IDS_FORMAT_LABELC2242           2121
#define IDS_FORMAT_LABELC2245           2122
#define IDS_FORMAT_LABELL7160           2123
#define IDS_FORMAT_LABELL7161           2124
#define IDS_FORMAT_LABELL7162           2125
#define IDS_FORMAT_LABELL7163           2126
#define IDS_FORMAT_LABELL7164           2127
#define IDS_FORMAT_LABELL7165           2128
#define IDS_FORMAT_LABELL7166           2129
#define IDS_FORMAT_LABELL7168           2130
#define IDS_FORMAT_LABELL7651           2131
#define IDS_FORMAT_LABELL7655           2132
#define IDS_FORMAT_LABELL7664           2133
#define IDS_FORMAT_LABELL7671FACE       2134
#define IDS_FORMAT_LABELL7674SPINE      2135
#define IDS_FORMAT_NAMEBADGE5361        2136
#define IDS_FORMAT_NAMEBADGE5390        2137
#define IDS_FORMAT_NAMEBADGE5395        2138
#define IDS_FORMAT_NAMEBADGEL7418       2139
#define IDS_FORMAT_PINFED4030           2140
#define IDS_FORMAT_PINFED4031           2141
#define IDS_FORMAT_PINFED4060           2142
#define IDS_FORMAT_PINFED4061           2143
#define IDS_FORMAT_PINFED4062           2144
#define IDS_FORMAT_PINFED4065           2145
#define IDS_FORMAT_PINFED4067           2146
#define IDS_FORMAT_PINFED4088           2147
#define IDS_FORMAT_PINFED4143           2148
#define IDS_FORMAT_PINFED4145           2149
#define IDS_FORMAT_PINFED4240           2150
#define IDS_FORMAT_PINFED4241           2151
#define IDS_FORMAT_BUSINESSENVELOPE10   2200
#define IDS_FORMAT_STOCKENVELOPE9X6     2201
#define IDS_FORMAT_STOCKENVELOPE4X3     2202
#define IDS_FORMAT_STOCKENVELOPE6X4     2203
#define IDS_FORMAT_STOCKENVELOPE_C4     2204
#define IDS_FORMAT_STOCKENVELOPE_C5     2205
#define IDS_FORMAT_STOCKENVELOPE_C6     2206
#define IDS_FORMAT_STOCKENVELOPE_DL     2207
#define IDS_FORMAT_NOTECARD_ENVELOPE    2208
#define IDS_FORMAT_AVERY3258ENVELOPE    2209
#define IDS_FORMAT_AVERY3259ENVELOPE    2210
#define IDS_FORMAT_AVERY3260ENVELOPE    2211
#define IDC_FORMAT_LIST                 3000
#define IDS_PROJECT_ANIMATED_GREETINGS  3000
#define IDC_PAPER_LIST                  3001
#define IDS_PROJECT_BLANK_PAGES         3001
#define IDS_PROJECT_BANNERS             3002
#define IDS_PROJECT_BOOKLETS            3003
#define IDS_PROJECT_BROCHURES           3004
#define IDS_PROJECT_BUSINESS_CARDS      3005
#define IDS_PROJECT_CALENDARS           3006
#define IDS_PROJECT_CERTIFICATES        3007
#define IDS_PROJECT_ENVELOPES           3008
#define IDS_PROJECT_FLASHCARDS          3009
#define IDS_PROJECT_FLYERS              3010
#define IDS_PROJECT_GIFT_BAGS           3011
#define IDS_PROJECT_GIFT_TAGS           3012
#define IDS_PROJECT_GIFT_WRAP           3013
#define IDS_PROJECT_GREETING_CARDS      3014
#define IDS_PROJECT_HEAT_TRANSFERS      3015
#define IDS_PROJECT_LABELS              3016
#define IDS_PROJECT_LETTERHEADS         3017
#define IDS_PROJECT_LETTERS             3018
#define IDS_PROJECT_NAME_TAGS           3019
#define IDS_PROJECT_NEWSLETTERS         3020
#define IDS_PROJECT_ONLINE_GREETINGS    3021
#define IDS_PROJECT_PAMPHLETS           3022
#define IDS_PROJECT_PHOTO_ALBUMS        3023
#define IDS_PROJECT_PHOTO_COLLAGES      3024
#define IDS_PROJECT_PHOTO_NOVELTIES     3025
#define IDS_PROJECT_PHOTO_QUICKPRINTS   3026
#define IDS_PROJECT_PLACEMATS           3027
#define IDS_PROJECT_POSTCARDS           3028
#define IDS_PROJECT_POSTIT_NOTES        3029
#define IDS_PROJECT_REPORTS             3030
#define IDS_PROJECT_RESUMES             3031
#define IDS_PROJECT_SCRAPBOOKS          3032
#define IDS_PROJECT_SIGNS               3033
#define IDS_PROJECT_TABLE_CARDS         3034
#define IDS_PROJECT_TSHIRTS             3035
#define IDS_PROJECT_WEBSITES            3036
#define IDS_PROJECT_YEARBOOKS           3037
#define IDS_PAPER_USLETTER              4000
#define IDS_PAPER_USLEGAL               4001
#define IDS_PAPER_USTABLOID             4002
#define IDS_INFOTEXT_DEFAULT            5000
#define IDS_INFOTEXT_CATEGORY_CARDSHOP  5001
#define IDS_INFOTEXT_CATEGORY_PHOTO     5002
#define IDS_INFOTEXT_CATEGORY_CREATIVE  5003
#define IDS_INFOTEXT_CATEGORY_CLASSROOM 5004
#define IDS_INFOTEXT_CATEGORY_WORKPLACE 5005
#define IDS_INFOTEXT_CATEGORY_INTERNET  5006
#define IDS_INFOTEXT_CATEGORY_ALL       5007
#define IDS_INFOTEXT_CATEGORY_OPEN      5008

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        286
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         236
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
