//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ColorGenie.rc
//
#define IDR_MAINFRAME                   101
#define IDR_ICCTYPE                     102
#define CG_IDS_PROGRESS_CAPTION         112
#define IDS_CANTSTARTBUILDPROFILE       113
#define IDS_DEVICE                      129
#define IDS_NOTHREADERR                 130
#define IDS_ERR_NOTHREAD                130
#define IDS_NOPORTERR                   131
#define IDS_ERR_NOPORT                  131
#define IDD_MY_MESSAGE                  131
#define IDD_EXCLAM_MESSAGE              131
#define IDS_NODATAERR                   132
#define IDS_ERR_NODATA                  132
#define IDS_GENERALERR                  133
#define IDD_POSITION_DLG                133
#define IDS_ERR_GENERAL                 133
#define IDI_ICON1                       133
#define IDS_MEMORYERR                   134
#define IDS_ERR_MEMORY                  134
#define IDS_TIMEOUTERR                  135
#define IDS_ERR_TIMEOUT                 135
#define IDS_ERR_DEVICE                  136
#define IDS_ERR_NODEVICE                137
#define IDS_ERR_DEVICE_RESET            138
#define IDD_SETUP_PAGE                  139
#define IDS_ERR_DEVICE_ILLUMINATION     139
#define IDS_ERR_DEVICE_MEASUREMENT_TYPE 140
#define IDD_PATCHFORMAT_PAGE            141
#define IDS_ERR_DEVICE_READ             141
#define IDS_ERR_INITIALIZATION          142
#define IDS_ERR_TURN_ONLINE             143
#define IDS_ERR_TURN_OFFLINE            144
#define IDS_ERR_MOVE_HEAD               145
#define IDS_ERR_HEAD_UP                 146
#define IDS_ERR_HEAD_DOWN               147
#define IDS_ERR_DEVICE_WARM_UP          148
#define IDS_ERR_DEVICE_MEASUREMENT      149
#define IDS_ERR_SEND_REQUEST            150
#define IDS_ERR_MEASUREMENT_DATA        151
#define IDS_ERR_CALIBRATE               152
#define IDS_ERR_OPENPORT                153
#define IDS_ERR_NO_CMM                  154
#define IDS_ERR_DENSITY                 155
#define IDD_ABOUTBOX                    200
#define IDD_CALIBRATE                   201
#define IDD_TONEADJUST                  202
#define IDD_COLORDATA                   203
#define IDD_SETTINGS                    204
#define IDD_TUNING                      205
#define IDD_PROGRESS                    206
#define IDD_DEVICESETUP                 207
#define IDD_MEASURE                     208
#define IDD_VIEWGAMUT                   209
#define IDD_VIEWDATA                    210
#define IDD_COLORDATA_WITH_GRIDS        211
#define IDD_BUILD_DIALOG                212
#define IDB_SPLASH                      300
#define IDB_HOME                        301
#define IDB_MOVEDEPTH                   302
#define IDB_MOVEPLANE                   303
#define IDB_ROTATE                      304
#define IDB_CAMERA                      305
#define IDB_BITMAP1                     306
#define IDB_LAB1                        306
#define IDB_BITMAP2                     307
#define IDB_LAB2                        307
#define IDB_BITMAP3                     308
#define IDB_LAB3                        308
#define IDB_TAB00                       400
#define IDB_TAB01                       401
#define IDB_TAB02                       402
#define IDB_TAB03                       403
#define IDB_TAB04                       404
#define IDB_TAB05                       405
#define IDB_TAB06                       406
#define IDB_TAB07                       407
#define IDB_TAB08                       408
#define IDB_TAB09                       409
#define IDB_TAB10                       410
#define IDB_TAB11                       411
#define IDB_TAB12                       412
#define IDB_TAB13                       413
#define IDB_TAB14                       414
#define IDB_CHECK2                      415
#define IDB_CHECK1                      416
#define IDB_DRYJET                      417
#define IDB_SOURCE                      418
#define IDB_DENSITY1                    437
#define IDB_DENSITY2                    438
#define IDB_DENSITY3                    439
#define IDD_MODIFY                      440
#define IDD_FISRT_PATCH                 441
#define IDC_PROGDLG_PROGRESS            1000
#define IDC_PROGDLG_PERCENT             1001
#define IDC_NO_SAVE                     1001
#define IDC_PROGDLG_STATUS              1002
#define IDC_DESCRIPTION                 1003
#define IDSAVE                          1003
#define IDC_SAVE                        1003
#define IDC_IMPORT                      1004
#define IDC_MY_TEXT                     1004
#define IDC_EXCLAM_TEXT                 1004
#define IDC_IMPORT_DRY                  1005
#define IDC_EXPORT                      1006
#define IDC_EXPORT_DRY                  1007
#define IDC_MEASURE                     1008
#define IDC_MEASURE_DRY                 1009
#define IDC_VIEW_GAMUT                  1010
#define IDC_VIEW_GAMUT_DRY              1011
#define IDC_DESCRIPTION_DRY             1012
#define IDC_GRID                        1013
#define IDC_GRID_SRC                    1014
#define IDC_GRID_DST                    1015
#define IDC_RESET                       1016
#define IDC_BLACK                       1017
#define IDC_CYAN                        1018
#define IDC_MAGENTA                     1019
#define IDC_START_BUT                   1020
#define IDC_YELLOW                      1021
#define IDC_CURVE                       1022
#define IDC_LEVELIN                     1023
#define IDC_LEVELOUT                    1024
#define IDC_CURVEPERCENT                1025
#define IDC_CURVEVALUE                  1026
#define IDC_SETTINGSCOMBO               1027
#define IDC_ON                          1028
#define IDC_OFF                         1029
#define IDC_SATURATION_SLIDER           1030
#define IDC_SATURATION_VALUE            1031
#define IDC_STATUS_STATIC               1031
#define IDC_BALANCE_SLIDER              1032
#define IDC_LABEL1                      1032
#define IDC_BALANCE_VALUE               1033
#define IDC_LABEL2                      1033
#define IDC_CONTRAST_SLIDER             1034
#define IDC_DEVICE_COMBO                1034
#define IDC_CONTRAST_VALUE3             1035
#define IDC_HON                         1035
#define IDC_CONTRAST_VALUE              1036
#define IDC_SMOOTHING_SLIDER            1037
#define IDC_TWEAK_CRVALUE               1037
#define IDC_PORT                        1037
#define IDC_SMOOTHING_VALUE             1038
#define IDC_BAUTRATE                    1038
#define IDC_SELECT_TWEAK                1039
#define IDC_TWEAK_SELECT                1039
#define IDC_PATCHFORMAT                 1039
#define IDC_HOFF                        1039
#define IDC_ADD_TWEAK                   1040
#define IDC_TWEAK_ADD                   1040
#define IDC_DELETE_TWEAK                1041
#define IDC_TWEAK_DELETE                1041
#define IDC_DEVICE_LABEL                1041
#define IDC_TWEAK_LPRINT                1042
#define IDC_PORT_LABEL                  1042
#define IDC_TWEAK_APRINT                1043
#define IDC_BAUD_RATE_LABEL             1043
#define IDC_TWEAK_BPRINT                1044
#define IDC_FORMAT_LABEL                1044
#define IDC_TWEAK_CPRINT                1045
#define IDC_SETUP_BUTTON                1045
#define IDC_TWEAK_LDESIRED              1046
#define IDC_TWEAK_ADESIRED              1047
#define IDC_TWEAK_BDESIRED              1048
#define IDC_TWEAK_CDESIRED              1049
#define IDC_TWEAK_LGAMUT                1050
#define IDC_TWEAK_AGAMUT                1051
#define IDC_TWEAK_BGAMUT                1052
#define IDC_TWEAK_CGAMUT                1053
#define IDC_TWEAK_GAMUT                 1054
#define IDC_TWEAK_LVALUE                1055
#define IDC_TWEAK_LSCROLL               1056
#define IDC_TWEAK_MOVETOOL              1057
#define IDC_TWEAK_SIZETOOL              1058
#define IDC_TWEAK_LRSLIDER              1060
#define IDC_TWEAK_CRSLIDER              1061
#define IDC_TWEAK_LRVALUE               1062
#define IDC_TWEAK_GAMUTRADIO            1063
#define IDC_TWEAK_PRINTRADIO            1064
#define IDC_TWEAK_CDESIRED2             1065
#define IDC_TWEAK_LDESIRED2             1066
#define IDC_TWEAK_ADESIRED2             1067
#define IDC_TWEAK_BDESIRED2             1068
#define IDC_TWEAK_CGAMUT2               1069
#define IDC_TWEAK_LGAMUT2               1070
#define IDC_TWEAK_AGAMUT2               1071
#define IDC_TWEAK_BGAMUT2               1072
#define IDC_TWEAK_LPRINT2               1073
#define IDC_TWEAK_APRINT2               1074
#define IDC_TWEAK_BPRINT2               1075
#define IDC_TWEAK_CPRINT2               1082
#define IDC_STATIC_POSITION             1083
#define IDC_VIEW_DATA                   1084
#define IDC_VIEW_DATA_DRY               1085
#define IDC_STATUS_EDIT                 1086
#define IDC_PATCH_EDIT                  1087
#define IDC_PROGRESS_BAR                1088
#define IDC_PROGRESS_EDIT               1089
#define IDC_DATA_OK_DRY                 1090
#define IDC_DATA_OK                     1091
#define IDC_DATE                        1097
#define IDC_SRC_DATE                    1098
#define IDC_DRY_DATE                    1099
#define IDC_CLEAR                       1100
#define IDC_PON                         1103
#define IDC_POFF                        1104
#define IDC_PATCH_NUM                   1106
#define IDI_EXCLAM_ICON                 1109
#define IDM_DEVICENAME1                 1621
#define IDM_DEVICEPORT1                 1622
#define ID_FILE_REVERT                  1623
#define ID_EDIT_PREFERENCES             1624
#define ID_FILE_OPEN_GAMUT              1625
#define IDS_PROGRESS_CAPTION            32000
#define IDS_CAL_DIRNAME                 57346
#define IDS_TONE_DIRNAME                57347
#define IDS_DATA_DIRNAME                57348
#define IDS_PROFILE_DIRNAME             57349
#define IDS_DEFAULTS_DIRNAME            57350

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        443
#define _APS_NEXT_COMMAND_VALUE         1626
#define _APS_NEXT_CONTROL_VALUE         1110
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
