// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "TextEditor.h"

/////////////////////////////////////////////////////////////////////////////
// CTexteditor2

IMPLEMENT_DYNCREATE(CTexteditor2, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CTexteditor2 properties

/////////////////////////////////////////////////////////////////////////////
// CTexteditor2 operations
