//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by version.rc
//

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif


#define CHECK_CLASS "button"
#define CHECK_STYLE BS_CHECKBOX
#define RADIO_CLASS "button"
#define RADIO_STYLE BS_RADIOBUTTON
#define UPDOWN_INTSTYLE	(UDS_SETBUDDYINT | UDS_ALIGNRIGHT | UDS_AUTOBUDDY | UDS_NOTHOUSANDS)
#define UPDOWN_FIXEDSTYLE (UDS_ALIGNRIGHT | UDS_AUTOBUDDY)
#define TRACKBAR_HORZSTYLE (TBS_HORZ | TBS_TOP | TBS_AUTOTICKS)
#define TRACKBAR_STYLE TRACKBAR_HORZSTYLE
#define TRACKBAR_VERTSTYLE (TBS_VERT | TBS_LEFT | TBS_AUTOTICKS)
