//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Remind.RC
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_REMIND_DIALOG               102
#define IDS_WIZBACK                     102
#define IDS_WIZNEXT                     103
#define IDS_WIZCANCEL                   104
#define IDS_WIZFINISH                   105
#define IDS_EVENT_WIZARD                106
#define IDS_UNKNOWN                     107
#define IDS_EVENT_WIZARD_CANT_ACCESS_ADDRESS_BOOK 108
#define IDS_EVENT_WIZARD_NO_FIELD_NAMES 109
#define IDS_EVENT_WIZARD_CANT_CREATE_EVENT 110
#define IDS_STANDARD_DATABASE_DESCRIPTION 111
#define IDS_STANDARD_DATE_FIELD_NAMES   112
#define IDS_ALL_EVENT_TYPE_NAME         113
#define IDS_ALL_ENTRIES_NAME            114
#define IDS_JANUARY                     115
#define IDS_FEBRUARY                    116
#define IDS_MARCH                       117
#define IDS_APRIL                       118
#define IDS_MAY                         119
#define IDS_JUNE                        120
#define IDS_JULY                        121
#define IDS_AUGUST                      122
#define IDS_SEPTEMBER                   123
#define IDS_OCTOBER                     124
#define IDS_NOVEMBER                    125
#define IDS_DECEMBER                    126
#define IDS_DATE_SEPARATORS             127
#define IDR_MAINFRAME                   128
#define IDS_DEFAULT_DATE_FORMAT         128
#define IDD_UPCOMING_EVENTS             129
#define IDS_INITIAL_DAYS_COUNT          129
#define IDD_EVENT_REMINDER_LIST         130
#define IDS_UPCOMING_EVENT_FORMAT_STANDARD 130
#define IDD_UPCOMING_EVENTS_NO_EVENTS   131
#define IDS_UPCOMING_EVENT_FORMAT_IMPORTED 131
#define IDS_TODAY                       132
#define IDD_ADD_NEW_EVENT_ADDRESS_BOOK  133
#define IDS_TOMORROW                    133
#define IDD_ADD_NEW_EVENT_TYPE          134
#define IDS_DAYS_AWAY                   134
#define IDD_ADD_NEW_EVENT_NAME          135
#define IDS_NEXT_EVENT_FORMAT           135
#define IDD_ADD_NEW_EVENT_DAYS          136
#define IDS_EVENTS_TITLE                136
#define IDD_ADD_NEW_EVENT_CONGRATULATIONS 137
#define IDS_NO_EVENTS_TITLE             137
#define IDS_EVENTS_REMINDER             138
#define IDD_NO_ADDRESS_BOOKS            138
#define IDS_NO_EVENTS_REMINDER          139
#define IDS_DEFAULT_EVENTS              140
#define IDB_BITMAP1                     140
#define IDS_NO_ADDRESS_BOOKS            141
#define IDS_SAVE_EVENTS                 141
#define IDS_STANDARD_SENDER_DATABASE_DESCRIPTION 142
#define IDS_NETWORK_FILE_IN_USE         143
#define IDS_NETWORK_FILE_CORRUPTED      144
#define IDS_NETWORK_FILE_CANT_CREATE    145
#define IDS_INSTDAT_NAME                146
#define IDS_INSTDAT_MISSING             147
#define IDS_CONFIG_NO_SEE               148
#define IDS_PMG                         149
#define IDS_PMGPS                       150
#define IDS_PMGPSCD                     151
#define IDS_PMGBP                       152
#define IDS_PMGBPCD                     153
#define IDS_PMGDX                       154
#define IDS_PMGDXCD                     155
#define IDS_GROUP_PMG_TRIAL             156
#define IDS_NAME_PMG_TRIAL1             157
#define IDS_NAME_PMG_TRIAL2             158
#define IDS_NAME_PMG_TRIAL3             159
#define IDS_PMGC                        160
#define IDS_PMGCCD                      161
#define IDS_PMP                         162
#define IDS_PMPCD                       163
#define IDS_PM                          164
#define IDS_PMGNGCD                     165
#define IDS_PMPR                        166
#define IDS_PMPRCD                      167
#define IDS_PMOS                        168
#define IDS_PMOSCD                      169
#define IDS_PMSU                        170
#define IDS_PMSUCD                      171
#define IDS_AGFPST                      172
#define IDS_AGFPST_CD                   173
#define IDS_AGFPPR                      174
#define IDS_AGFPPR_CD                   175
#define IDS_AGSPST                      176
#define IDS_AGSPST_CD                   177
#define IDS_AGCRST                      178
#define IDS_AGCRST_CD                   179
#define IDS_REMINDER                    180
#define IDS_FORGET_ME_NOT               181
#define IDS_FORGET_ME_NOT_TM            182
#define IDS_NOT_SUPPORTED               183
#define IDS_UNSUP_NOADDR                184
#define IDS_UNSUP_NOREMINDER            185
#define IDS_UNSUP_CARDSERVER            186
#define IDS_ASTORE                      187
#define IDS_ASTORE_CD                   188
#define IDS_AGCRDX                      189
#define IDS_AGCRDX_CD                   190
#define IDS_PMGOLD                      200
#define IDS_PMGOLDCD                    201
#define IDS_PMSILVER                    202
#define IDS_PMSILVERCD                  203
#define IDC_BITMAP                      666
#define IDC_EVENT_REMINDER_LIST         1000
#define IDC_LIST1                       1001
#define IDC_LIST                        1001
#define IDC_EVENT_LIST                  1002
#define IDC_NEW                         1003
#define IDC_CHANGE                      1004
#define IDC_DELETE                      1005
#define IDC_NEXT_EVENT                  1006
#define IDC_DAYS                        1008
#define IDC_ADDRESS_BOOK_TITLE          1013
#define IDC_EVENT_TITLE                 1014
#define IDC_NAME_TITLE                  1015
#define IDC_DAYS_TITLE                  1016
#define IDC_ADDRESS_BOOK_DISPLAY        1018
#define IDC_NEXT_EVENT_BORDER           1019
#define IDC_REMINDER                    1020
#define IDC_TYPE_DISPLAY                1021
#define IDC_LIST_HINT                   1021
#define IDC_NAME_DISPLAY                1022
#define IDC_NO_EVENTS_HINT1             1022
#define IDC_DAYS_DISPLAY                1023
#define IDC_NO_EVENTS_HINT2             1023
#define IDC_STATIC_TM                   1024

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1025
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
