#ifndef IN_ERRORDIAL
#define IN_ERRORDIAL

#include "mcostat.h"

typedef enum {
	MCO_SCAN_NOT_CALIB = 0,
	MCO_GET_CAL_FN,	
	MCO_SCAN_CALIB,
	MCO_MIS_MATCH_CMP, 
	MCO_MIS_MATCH_CMP_OK,
	MCO_UNSUC_SCAN_CALIB,
	MCO_NO_SCAN_FILE,
	MCO_NO_SCAN_FILE_SUP,
	MCO_ALMOST_USE,
	MCO_NO_USE,
	MCO_EVE_ERROR,
	MCO_BUFF_SIZE,
	MCO_NO_ERROR,
	MCO_SAFE_MEM,
	MCO_SAVE_FILE_OPT,
	MCO_SAVE_FILE_NEC,
	MCO_TABLE_NOT_FOUND,
	MCO_UNSPRT_SCAN_TYPE,
	MCO_ICC_NOT_FOUND,
	MCO_BAD_PROFILE,
	MCO_CLOSE_DOC,
	MCO_FIND_PATCHS,
	MCO_ALIGN_PATCHES,
	MCO_CALIB,
	MCO_CALIB_2,
	MCO_CALIB_XRITE,
	MCO_FAIL_CALIB,
	MCO_WARN_TCR,
	MCO_MEAS_PAPER_DENSITY,
	MCO_REVERT_FILE,
	} McoMess;

void McoErrorAlert(McoStatus state);
McoStatus McoMessAlert(McoMess mess,unsigned char *sn);
short McoCloseAlert(int savef);

#endif