//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MonacoView.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDS_ERR_NO_ICM_DIR              102
#define IDS_PREF_DIRNAME                103
#define IDS_ERR_OUT_OF_GAMUT            104
#define IDR_MAINFRAME                   128
#define IDD_MONACOVIEW                  128
#define IDB_SPLASH                      131
#define IDD_CALIBRATE                   132
#define IDB_COLORMAP                    136
#define IDD_PREFERENCES                 137
#define IDD_VAL_PATCH                   138
#define IDD_MEASURE                     139
#define IDB_Sensor                      140
#define IDB_WARNING                     145
#define IDB_LOGO                        152
#define IDB_LOGO1                       154
#define IDB_LITE_PATCHES                155
#define IDB_DARK_PATCHES                156
#define IDC_VALIDATE                    1000
#define IDC_WHITE                       1001
#define IDC_CAL_VERSION                 1001
#define IDC_GAMMA                       1002
#define IDC_SET_NUM_PERIODS             1003
#define IDC_BUTTON2                     1004
#define IDC_COM1                        1005
#define IDC_MEASURE                     1006
#define IDC_COM2                        1007
#define IDC_LABEL1                      1008
#define IDC_DISPLAY_L                   1009
#define IDC_COLOR_SCROLL                1010
#define IDC_DISPLAY_x                   1011
#define IDC_CALIBRATE                   1012
#define IDC_DISPLAY_y                   1013
#define IDC_AUTOMEAS_CHECK              1014
#define IDC_MONFREQ                     1015
#define IDC_INTTIME                     1016
#define IDC_MEAS_FREQ                   1017
#define IDC_SET_INTTIME                 1018
#define IDC_TEXTBOX1                    1019
#define IDC_UNITS_FTLTS                 1020
#define IDC_TEXTBOX2                    1021
#define IDC_UNITS_CANDELAS              1022
#define IDC_LABEL2                      1023
#define IDC_LABEL3                      1024
#define IDC_CANCEL                      1025
#define IDC_MEAS_TIME                   1026
#define IDC_OUT_L                       1027
#define IDC_NUM_PERIODS                 1028
#define IDC_OUT_A                       1029
#define IDC_OUT_B                       1030
#define IDC_RED_X                       1031
#define IDC_GREEN_X                     1032
#define IDC_BLUE_X                      1033
#define IDC_RED_Y                       1034
#define IDC_GREEN_Y                     1035
#define IDC_BLUE_Y                      1036
#define IDC_D_E                         1037
#define IDC_COLOR_VIEW                  1038
#define IDC_PATCH                       1039
#define IDC_PATCH_WARN                  1040
#define IDC_IN_L                        1041
#define IDC_PATCH_WARN2                 1042
#define IDC_IN_A                        1043
#define IDC_PATCH_WARN3                 1044
#define IDC_IN_B                        1045
#define IDC_PATCH_WARN4                 1046
#define IDC_PATCH_WARN5                 1047
#define IDC_CHECK_PHOTO                 1048
#define IDC_CHECK_ICC                   1049
#define IDC_PATCH2                      1050
#define IDC_VAL_PATCH                   1051
#define IDC_PATCH3                      1052
#define IDC_RADIO1                      1053
#define IDC_RADIO2                      1054
#define IDC_RADIO3                      1055
#define IDC_RADIO4                      1056
#define IDC_RADIO5                      1057
#define IDC_EDIT1                       1058
#define IDC_EDIT2                       1059
#define IDC_EDIT3                       1060
#define ID_BEGIN                        1061
#define IDC_EDIT4                       1062
#define IDC_OK                          1063
#define IDC_PATCH4                      1064
#define IDC_DARK_PATCHES                1065
#define IDC_PATCH5                      1066
#define IDC_LITE_PATCHES                1067
#define IDC_QUIT                        1068
#define IDC_SENSOR                      1069
#define IDC_PATCH1                      1070
#define IDC_PATCH_WARN1                 1071
#define ID_FILE_CALIBRATE               32773
#define ID_FILE_PREF                    32774
#define ID_FILE_CAL                     32775
#define ID_FILE_QUIT                    32776
#define ID_TOOLS_GAMMA_07               32777
#define ID_TOOLS_GAMMA_10               32778
#define ID_TOOLS_GAMMA_12               32779
#define ID_TOOLS_GAMMA_14               32780
#define ID_TOOLS_GAMMA_16               32781
#define ID_TOOLS_GAMMA_18               32782
#define ID_TOOLS_GAMMA_20               32783
#define ID_TOOLS_GAMMA_22               32784
#define ID_TOOLS_GAMMA_28               32785
#define ID_TOOLS_WHITE_5000             32786
#define ID_TOOLS_WHITE_5500             32787
#define ID_TOOLS_WHITE_6500             32788
#define ID_TOOLS_WHITE_7500             32789
#define ID_TOOLS_WHITE_9300             32790
#define ID_TOOLS_WHITE_MON              32791
#define ID_FILE_MEASURE                 32792
#define ID_FILE_VALIDATE                32793

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        159
#define _APS_NEXT_COMMAND_VALUE         32794
#define _APS_NEXT_CONTROL_VALUE         1072
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
