/* 
####################################################################################
#                              Animator                                            #
#                    Copyright 1991 - 1993 Ray White                               #
#                         3804 Seventh Street                                      #
#                        Sachse, Texas  75048                                      #
####################################################################################
*/

#ifndef _APP_H_
#define _APP_H_


#include <windows.h>
#include <stdlib.h>
#include <conio.h>                      // for MCS ports

#define bool BOOL

void CVAnimateInit();

#endif
