//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Ctp.rc
//
#define ID_PREV_VIEW                    3
#define ID_HAND                         10
#define ID_HAND_UR                      11
#define ID_HAND_FR                      12
#define ID_HAND_UE                      13
#define ID_HAND_FE                      14
#define ID_HAND_IM                      15
#define ID_HAND_LI                      16
#define ID_HAND_CAL                     17
#define ID_ROTATE                       18
#define IDS_MSGBOXTITLE                 51
#define IDS_MSGBOXTITLE2                52
#define IDS_MANIFEST_URL                53
#define IDS_AUTOUPDATE_ONLINE_PROMPT    54
#define IDS_MANIFEST_ERROR              55
#define IDS_NEWVERSION_PROMPT           56
#define IDS_CURRENTVERSION_PROMPT       57
#define IDS_VERSIONUPDATED_PROMPT       58
#define IDS_HPMANIFEST_URL              59
#define IDS_SPELLCHECK                  60
#define IDS_BTN_VIEWCARD                61
#define IDS_BTN_VIEWENV                 62
#define IDS_BTN_PRINTPROJECT            63
#define IDR_CTP                         101
#define IDR_CARDBACK_MESSAGE            102
#define IDR_CARDBACK_COPYRIGHT          103
#define IDR_AGLOGO                      104
#define IDR_BMLOGO                      105
#define IDR_HPLOGO                      106
#define IDR_HPAGLOGO                    107
#define IDR_POPUPMENU                   110
#define IDR_POPUPMENU_EX                111
#define IDR_POPUPMENU_EXTRAS            112
#define IDR_ACCELERATORS                113
#define IDR_ENVELOPE_SEND               114
#define IDR_ENVELOPE_RETURN             115
#define IDR_ENVELOPE_BACKGROUND         116
#define IDT_SEL_FLASH                   117
#define IDD_ENVELOPEDLG2                118
#define IDC_CALENDAR_MONTH              197
#define IDC_CALENDAR_YEAR               198
#define IDC_CALENDAR_STYLEMONTH         199
#define IDC_CALENDAR_STYLEWEEK          200
#define IDC_CALENDAR_STYLEDAYS          201
#define IDC_DOC_PAGENAV                 202
#define IDC_DOC_PAGENAME                203
#define IDC_LINE_SIZE                   205
#define IDC_FONT                        206
#define IDC_TEXT_SIZE                   207
#define IDC_BOLD                        208
#define IDC_ITALIC                      209
#define IDC_UNDERLINE                   210
#define IDC_LEFT                        211
#define IDC_CENTER                      212
#define IDC_RIGHT                       213
#define IDC_TOP                         214
#define IDC_MIDDLE                      215
#define IDC_BOTTOM                      216
#define IDC_PAPERTYPE                   217
#define IDC_PRINT                       218
#define IDC_HALFFOLD                    219
#define IDC_QUARTERFOLD                 220
#define IDC_FRAME1                      221
#define IDC_FRAME2                      222
#define IDC_FRAME3                      223
#define IDC_FRAME4                      224
#define IDC_DBLSIDE                     225
#define IDC_DBLSIDE2                    226
#define IDC_BORDERLESS                  227
#define IDC_NEWDOC_LIST                 228
#define IDC_NEWDOC_LANDSCAPE            229
#define IDC_NEWDOC_PORTRAIT             230
#define IDC_NEWDOC_STDSIZE              231
#define IDC_NEWDOC_WIDTH                232
#define IDC_NEWDOC_HEIGHT               233
#define IDC_NEWDOC_STDNUMPAGES          234
#define IDC_NEWDOC_NUMPAGES             235
#define IDC_NEWDOC_STDPAGENAMES         236
#define IDC_NEWDOC_PAGENAME1            237
#define IDC_NEWDOC_PAGENAME2            238
#define IDC_NEWDOC_PAGENAME3            239
#define IDC_NEWDOC_PAGENAME4            240
#define IDC_NEWDOC_PAGENAME5            241
#define IDC_NEWDOC_PAGENAME6            242
#define IDC_NEWDOC_PAGENAME7            243
#define IDC_NEWDOC_PAGENAME8            244
#define IDC_NEWDOC_SAMPLE               245
#define IDC_NEWDOC_PAGELABEL1           246
#define IDC_NEWDOC_PAGELABEL2           247
#define IDC_NEWDOC_PAGELABEL3           248
#define IDC_NEWDOC_PAGELABEL4           249
#define IDC_NEWDOC_PAGELABEL5           250
#define IDC_NEWDOC_PAGELABEL6           251
#define IDC_NEWDOC_PAGELABEL7           252
#define IDC_NEWDOC_PAGELABEL8           253
#define IDC_NEWDOC_PAPERTYPE            254
#define IDC_PROGRESSTEXT                255
#define IDC_DOCTYPE                     256
#define IDC_WIDTH                       257
#define IDC_HEIGHT                      258
#define IDC_PAPERFEED_CHANGE            259
#define IDC_PAPERFEED_POS_LEFT          260
#define IDC_PAPERFEED_POS_CENTER        261
#define IDC_PAPERFEED_POS_RIGHT         262
#define IDC_PAPERFEED_FACE_DOWN         263
#define IDC_PAPERFEED_FACE_UP           264
#define IDC_PAPERFEED_EDGE_LEFT         265
#define IDC_PAPERFEED_EDGE_RIGHT        266
#define IDC_PAPERFEED_EDGE_TOP          267
#define IDC_PAPERFEED_ACTIVE            268
#define IDC_SAMPLE                      269
#define IDC_INFO                        270
#define IDC_PAGENAMES                   271
#define IDC_SMALLLABEL1                 272
#define IDC_BIGLABEL1                   273
#define IDC_BIGLABEL3                   274
#define IDC_BIGLABEL2                   275
#define IDC_BIGLABEL4                   276
#define IDC_LINE_COLOR                  277
#define IDC_FILL_TYPE                   278
#define IDC_FILL_COLOR                  279
#define IDC_FILL_COLOR2                 280
#define IDC_FILL_COLOR3                 281
#define IDC_TYPELABEL                   282
#define IDC_INSTRUCTLABEL               283
#define IDC_SHAPE_NAME                  284
#define IDC_SEND_ADDRESS                285
#define IDC_PAPERTYPE_LABEL             286
#define IDC_PRINTER_CALIBRATE           287
#define IDD_ENVELOPEWIZARD              288
#define IDD_PAPERFEED                   289
#define IDC_RETURN_ADDRESS              290
#define IDC_SYMTEXT                     291
#define IDC_SYMIMAGE                    292
#define IDC_SYMGRAPHIC                  293
#define IDC_SYMCALENDAR                 294
#define IDC_BIGLABEL5                   295
#define IDC_PICTURE_SELECT2             296
#define IDD_PROPERTIESDLG               301
#define IDD_WAITDLG                     302
#define IDD_PRINT                       303
#define IDD_DBLSIDEINTRO                304
#define IDD_DBLSIDESTEP1                305
#define IDD_DBLSIDESTEP2                306
#define IDD_DBLSIDEEND                  307
#define IDD_NEWDOCWIZINTRO              308
#define IDD_NEWDOCWIZSTEP1              309
#define IDD_NEWDOCWIZSTEP2              310
#define IDD_NEWDOCWIZEND                311
#define IDD_PROGRESSDLG                 312
#define IDD_CHOOSECOLOR                 313
#define IDC_PICTURE_SELECT              314
#define IDD_ENVELOPES                   315
#define IDD_CONVERT                     316
#define IDD_PANEL_PAGE                  317
#define IDD_PANEL_DEFAULT               318
#define IDD_PANEL_TEXT                  319
#define IDD_PANEL_GRAPHIC               320
#define IDD_PANEL_IMAGE                 321
#define IDD_PANEL_INFO                  322
#define IDD_ENVELOPE_SIZE_SELECT        323
#define IDD_ENVELOPE_ADDRESS_SELECT     324
#define IDD_ENVELOPE_PICT_SELECT        326
#define IDD_ENVELOPE_COLOR_SELECT       327
#define IDD_ENVELOPE_FINAL              328
#define IDC_UPDATE_CONTROLS             329
#define IDC_CALENDAR_LAYOUT             330
#define ID_NEXT_VIEW                    331
#define IDC_STYLE_MONTHYEAR             331
#define IDC_STYLE_WEEK                  332
#define IDC_ENABLE_BACKGROUND           334
#define IDD_PANEL_CALENDAR              335
#define IDC_UNUSEDBOXES_INVISIBLE       336
#define IDC_ALLBOXES                    340
#define IDC_LASTROW_BOXES               341
#define IDC_TITLE_SIZE                  342
#define IDC_MONDAY_START                343
#define IDC_SUNDAY_START                344
#define IDC_BACK                        345
#define IDC_WEEK_SIZE                   346
#define IDC_PAPERFEED_BOTTOM            348
#define IDC_PAPERFEED_TOP               349
#define IDC_STEP1                       352
#define IDC_STEP2                       353
#define IDC_STEP3                       354
#define IDC_STEP4                       355
#define IDC_HDR                         356
#define IDC_CHECKMATCH                  359
#define IDC_IMAGE_BOX                   360
#define IDC_WIZSTEP1_HDR                361
#define IDC_WIZSTEP2_HDR                362
#define IDC_WIZSTEP3_OPT1               363
#define IDC_WIZSTEP3_OPT2               364
#define IDC_WIZSTEP3_OPT3               365
#define IDC_WIZSTEP3_OPT4               366
#define IDC_PRINTORIENT_GROUP           367
#define IDC_PRINTORIENT_IMAGE           368
#define IDC_PA_IMAGE                    370
#define IDC_EFEEDALIGN_GROUP            373
#define IDC_EFA_IMAGE                   374
#define IDC_STEP1_STATIC                375
#define IDC_STEP2A_STATIC               376
#define IDC_STEP2B_STATIC               377
#define IDC_STEP3_STATIC                378
#define IDC_STEP4_STATIC                379
#define IDC_RETURN_STATIC               380
#define IDC_MAILING_STATIC              381
#define IDC_STEP3A_STATIC               382
#define IDC_STEP3B_STATIC               383
#define IDC_STATIC_3                    385
#define IDC_STATIC_1                    386
#define IDC_STATIC_2                    387
#define IDC_STATIC_4                    388
#define IDC_STATIC_5                    389
#define IDC_STATIC_6                    390
#define IDC_STATIC_TOP_1                391
#define IDC_STATIC_TOP_2                392
#define IDC_STATIC_TOP_3                393
#define IDC_STATIC_TOP_4                394
#define IDC_STATIC_TOP_5                395
#define IDC_STATIC_TOP_7                396
#define IDC_STATIC_FRONT_1              397
#define IDC_STATIC_FRONT_2              398
#define IDC_STATIC_FRONT_3              399
#define IDC_STATIC_FRONT_4              400
#define IDC_STATIC_FRONT_5              401
#define IDC_STATIC_FRONT_6              402
#define IDC_STATIC_7                    403
#define IDC_STATIC_8                    404
#define IDI_AGICON                      405
#define IDI_BMICON                      406
#define IDC_COPIES_GROUP                406
#define IDI_HPICON                      407
#define IDI_BANNER                      408
#define IDC_PAPERLOAD_STATIC            408
#define IDC_PAPERALIGN_STATIC           409
#define IDI_BROCHURE                    410
#define IDC_ENVELOPELOADS_STATIC        410
#define IDI_BUSINESSCARD                411
#define IDC_ENVELOPEEDGE_STATIC         411
#define IDC_ENVELOPEPREVIEW_GROUP       412
#define IDI_CDLABEL                     413
#define IDC_ENVELOPEPREVIEW_STATIC      413
#define IDI_CDBOOKLET                   414
#define IDC_PRINTSETTINGS_GROUP         414
#define IDC_BUTTON2                     415
#define IDC_COLOR_2                     416
#define IDI_ENVELOPE                    417
#define IDI_FULLSHEET                   418
#define IDI_HALFCARD                    419
#define IDI_LABEL                       420
#define IDI_NOTECARD                    422
#define IDI_PHOTOCARD                   423
#define IDI_POSTCARD                    425
#define IDI_QUARTERCARD                 427
#define IDI_IRONON                      429
#define IDI_TRIFOLD                     430
#define IDI_GIFTNAMECARD                432
#define IDI_HOLIDAYCARD                 433
#define IDB_1UP                         501
#define IDB_2UP                         502
#define IDB_3UP                         503
#define IDB_2DOWN                       504
#define IDB_1UP2DOWN                    505
#define IDB_CTLPANELBG                  508
#define IDB_CTLPANELBG_HP               509
#define IDB_FEED_LEFT                   510
#define IDB_FEED_CENTER                 511
#define IDB_FEED_RIGHT                  512
#define IDB_ENV_BRUR                    514
#define IDB_ENV_BRUL                    515
#define IDB_ENV_BRDT                    516
#define IDB_ENV_BRDR                    517
#define IDB_ENV_BRDL                    518
#define IDB_ENV_BLUT                    519
#define IDB_ENV_BLUR                    520
#define IDB_ENV_BLUL                    521
#define IDB_ENV_BLDT                    522
#define IDB_ENV_BLDR                    523
#define IDB_ENV_BLDL                    524
#define IDB_ENV_BCUT                    525
#define IDB_ENV_BCUR                    526
#define IDB_ENV_BCUL                    527
#define IDB_ENV_BCDT                    528
#define IDB_ENV_BCDR                    529
#define IDB_ENV_BRUT                    530
#define IDB_TOP_FEED_CENTER             606
#define IDB_SYMTEXT                     613
#define IDB_SYMIMAGE                    614
#define IDB_SYMGRAPHIC                  615
#define IDB_SYMCALENDAR                 616
#define IDD_CALENDAR_LAYOUT             622
#define IDB_BACK                        629
#define IDB_HATCH_BORDER                630
#define IDB_HATCH_BORDER_1              631
#define IDR_CAL_BTNWEEK                 632
#define IDR_CAL_BTNDAYS                 633
#define IDR_CAL_BTNMONTH                634
#define IDR_CAL_BTNOPTIONS              635
#define IDD_HTMLDIALOG                  642
#define IDD_ENVELOPES_2                 644
#define IDB_ENV_TLDL                    645
#define IDB_ENV_TLDR                    646
#define IDB_ENV_TLUL                    648
#define IDB_ENV_TLUR                    649
#define IDB_ENV_TCDL                    651
#define IDB_ENV_TCDR                    652
#define IDB_ENV_TCDT                    653
#define IDB_ENV_TCUL                    654
#define IDB_ENV_TCUR                    655
#define IDB_ENV_TCUT                    656
#define IDB_ENV_TRDL                    657
#define IDB_ENV_TRDR                    658
#define IDB_ENV_TRDT                    659
#define IDB_ENV_TRUL                    660
#define IDB_ENV_TRUR                    661
#define IDB_ENV_TRUT                    662
#define IDD_PAPERFEED_2                 681
#define IDB_TOP_FEED_RIGHT              682
#define IDB_TOP_FEED_LEFT               683
#define IDD_TOOLSPANEL_TEXT             685
#define IDD_TOPTOOLSPANEL_TEXT          685
#define IDD_ENVELOPESETTINGS_DIALOG     686
#define IDB_BITMAP1                     687
#define IDR_GIF1                        688
#define IDD_TOOLSPANEL_COMMON           689
#define IDD_TOOLSPANEL_DEFAULT          690
#define IDD_TOPTOOLSPANEL_DEFAULT       690
#define IDD_TOOLSPANEL_GRAPHIC          691
#define IDD_TOPTOOLSPANEL_GRAPHIC       691
#define IDC_BUTTON1                     692
#define IDC_SPELLCHECK                  692
#define IDC_BTN_ENVWIZ                  692
#define IDC_BTN_PRINT                   692
#define IDC_BTN_CARD                    692
#define IDR_POPUPMENU_FILE              693
#define IDR_POPUPMENU_EDIT              694
#define IDR_POPUPMENU_VIEW              695
#define IDR_POPUPMENU_TOOLS             696
#define IDR_POPUPMENU_FORMAT            697
#define IDR_POPUPMENU_HELP              698
#define IDC_COLOR_1                     699
#define IDD_PRINT2                      701
#define IDR_BOLD                        720
#define IDR_UNDERLINE                   721
#define IDR_ITALIC                      722
#define IDR_RIGHT                       723
#define IDR_LEFT                        724
#define IDR_CENTER                      725
#define IDR_TOP                         726
#define IDR_MIDDLE                      727
#define IDR_BOTTOM                      728
#define IDB_DIVIDER                     729
#define IDB_TEXT_OUTLINE                730
#define IDB_TEXT_COLOR                  731
#define IDR_PAGE_P1S                    732
#define IDR_PAGE_CP1S                   733
#define IDR_PAGE_CP2                    734
#define IDR_PAGE_CP2S                   735
#define IDR_PAGE_CP3                    736
#define IDR_PAGE_CP3S                   737
#define IDR_PAGE_CP4                    738
#define IDR_PAGE_CP4S                   739
#define IDR_PAGE_P1                     740
#define IDR_PAGE_CP1                    741
#define IDR_PAGE_L1S                    742
#define IDR_PAGE_CL1S                   743
#define IDR_PAGE_CL2                    744
#define IDR_PAGE_CL2S                   745
#define IDR_PAGE_CL3                    746
#define IDR_PAGE_CL3S                   747
#define IDR_PAGE_CL4                    748
#define IDR_PAGE_CL4S                   749
#define IDR_PAGE_L1                     750
#define IDR_PAGE_CL1                    751
#define IDR_PAGEPREV                    752
#define IDR_PAGENEXT                    753
#define IDB_TOOLPANEL_AG                754
#define IDB_TOOLPANEL1_AG               754
#define IDD_TOOLSPANEL_CALENDAR         755
#define IDD_TOPTOOLSPANEL_CALENDAR      755
#define IDR_NAVTOOLBAR_BG               756
#define IDD_NAV_PANEL                   757
#define IDB_GRAPHIC_ICON                762
#define IDB_GRAPHIC_OUTLINE             763
#define IDB_GRAPHIC_FILL                764
#define IDB_CALENDAR_OUTLINE            765
#define IDB_CALENDAR_ICON               766
#define IDB_CALENDAR_FILL               767
#define IDR_PAGEDELETE                  768
#define IDR_GIF2                        770
#define IDR_PAGEADD                     770
#define IDB_ENV_BCDL                    818
#define IDB_ENV_TLDT                    819
#define IDB_ENV_TLUT                    824
#define IDR_GIF3                        825
#define IDR_PRINTFINALSTEP_HEADER       826
#define IDR_CAL_BTNTRANSPARENT          827
#define IDI_ICON1                       830
#define IDI_AVERYPOSTER                 830
#define IDD_BOTTOOLSPANEL_TEXT          831
#define IDD_BOTTOOLSPANEL_GRAPHIC       832
#define IDD_BOTTOOLSPANEL_DEFAULT       833
#define IDD_BOTTOOLSPANEL_CALENDAR      834
#define IDD_TOOLSPANEL_PRINT            835
#define IDR_TOOLPANEL2_AG               836
#define IDD_DOCWIZRIBBONHOLES           836
#define IDR_CARD_BUTTON                 837
#define IDR_ENV_BUTTON                  838
#define IDR_PRINT_TOOLBAR_AG            839
#define IDR_TOOLBARBTN_PRINT            840
#define IDR_SPELLCHECK                  841
#define IDR_PRINTPREVIEW                842
#define IDR_PREVIEWFRAME                843
#define IDS_PRINTORIENT_PAPER           1000
#define ID_IGNORE_BTN                   1001
#define IDS_PRINTORIENT_ENVELOPE        1001
#define ID_IGNORE_ALL_BTN               1002
#define IDS_PRINTORIENT_PAPERGROUP      1002
#define ID_REPLACE_BTN                  1003
#define IDS_PRINTORIENT_ENVELOPEGROUP   1003
#define ID_REPLACE_ALL_BTN              1004
#define ID_ADD_TO_LEX_BTN               1005
#define ID_SUGGEST_BTN                  1006
#define ID_UNDO_BTN                     1007
#define ID_SUGGEST_LIST                 1009
#define ID_PROBLEM_LBL                  1011
#define ID_PROBLEM_WORD_EDT             1012
#define ID_IGN_LEX_CB                   1013
#define ID_EDIT_LEX_BTN                 1014
#define ID_OPTIONS_BTN                  1031
#define ID_SUGGESTIONS_LBL              1033
#define ID_ADD_WORDS_LBL                1034
#define ID_CONTEXT_EDT                  1050
#define ID_HELP_BTN                     1055
#define IDC_DOC_SAVE                    2998
#define IDC_DOC_SAVEAS                  2999
#define IDC_DOC_NEW                     3001
#define IDC_DOC_OPEN                    3002
#define IDC_DOC_CLOSE                   3003
#define IDC_DOC_ADDTEXTBOX              3004
#define IDC_DOC_ADDIMAGE                3005
#define IDC_DOC_ADDAPHOTO               3006
#define IDC_DOC_ENVELOPE_WIZ            3007
#define IDC_DOC_METRIC                  3008
#define IDC_DOC_HIDDEN                  3009
#define IDC_DOC_SHOWHIDDEN              3010
#define IDC_DOC_TRANSFORM               3013
#define IDC_DOC_FLIP                    3014
#define IDC_DOC_MIRROR                  3015
#define IDC_DOC_BACKONE                 3016
#define IDC_DOC_FORWARDONE              3017
#define IDC_DOC_BRINGTOFRONT            3018
#define IDC_DOC_PUSHTOBACK              3019
#define IDC_DOC_POSCENTERH              3020
#define IDC_DOC_POSCENTERV              3021
#define IDC_DOC_POSLEFT                 3022
#define IDC_DOC_POSRIGHT                3023
#define IDC_DOC_POSTOP                  3024
#define IDC_DOC_POSBOTTOM               3025
#define IDC_DOC_MAXIMIZE                3026
#define IDC_DOC_MAXWIDTH                3028
#define IDC_DOC_MAXHEIGHT               3029
#define IDC_DOC_MASTERLAYER             3030
#define IDC_DOC_DOWNLOADFONTS           3031
#define IDC_DOC_PAGEADD                 3032
#define IDC_DOC_PAGEDELETE              3033
#define IDC_DOC_PRINT                   3034
#define IDC_DOC_PAGENEXT                3035
#define IDC_DOC_PAGEPREV                3036
#define IDC_DOC_SELECTALL               3037
#define IDC_DOC_SELECTNEXT              3038
#define IDC_DOC_SELECTPREV              3039
#define IDC_DOC_CUT                     3040
#define IDC_DOC_COPY                    3041
#define IDC_DOC_PASTE                   3042
#define IDC_DOC_DELETE                  3043
#define IDC_DOC_UNDO                    3044
#define IDC_DOC_REDO                    3045
#define IDC_GIVEGIFT                    3046
#define IDC_DOC_ARTGALLERY              3047
#define IDC_FILEDOWNLOAD                3048
#define IDC_DOC_GRID                    3049
#define IDC_ABOUT                       3050
#define IDC_DOC_PROPERTIES              3052
#define IDC_DOC_HELP                    3053
#define IDC_DOC_EXTRAS                  3054
#define IDC_DOC_LOCKED                  3056
#define IDC_DOC_TEXT_EDIT_END           3057
#define IDC_DOC_TRANSPARENT             3058
#define IDC_DOC_TEXT_EDIT_START         3059
#define IDC_DOC_DESTRECTCHANGE          3060
#define IDC_DOC_SPELLCHECK              3061
#define IDC_DOC_ROTATECW                3062
#define IDC_DOC_ROTATECCW               3063
#define IDC_DOC_CROP                    3064
#define IDC_DOC_DOWNLOADSPELLCHECK      3065
#define IDC_DOC_CONVERT                 3066
#define IDC_DOC_LINECOLORCHANGE         3067
#define IDC_DOC_ADDCALENDAR             3068
#define IDC_DOC_ADDSHAPE                3069
#define IDC_DOC_LINEWIDTHCHANGE         3070
#define IDC_DOC_TEXTSIZECHANGE          3071
#define IDC_DOC_POSCENTER               3072
#define IDC_DOC_POSTOPLEFT              3073
#define IDC_DOC_POSTOPRIGHT             3074
#define IDC_DOC_POSBOTTOMLEFT           3075
#define IDC_DOC_POSBOTTOMRIGHT          3076
#define IDC_DOC_ZOOMIN                  3077
#define IDC_DOC_ZOOMOUT                 3078
#define IDC_DOC_ZOOMFULL                3079
#define IDC_DOC_ZOOM1                   3080
#define IDC_DOC_ZOOM2                   3081
#define IDC_DOC_ZOOM3                   3082
#define IDC_DOC_ZOOM4                   3083
#define IDC_DOC_ZOOM5                   3084
#define IDC_DOC_FILLCOLORCHANGE         3085
#define IDC_DOC_FILLCOLORCHANGE2        3086
#define IDC_DOC_FILLCOLORCHANGE3        3087
#define IDC_DOC_FILLTYPECHANGE          3088
#define IDC_DOC_SHAPENAMECHANGE         3089
#define IDC_DOC_SAVEAS_PDF              3090
#define IDC_DOC_SAVEAS_XML              3091
#define IDC_DOC_CALENDARMONTHCHANGE     3092
#define IDC_DOC_CALENDARYEARCHANGE      3093
#define IDC_DOC_CALENDARSTYLECHANGE     3094
#define IDC_ENVELOPE_PIC_NONE           3099
#define IDC_ENVELOPE_PIC_0              3100
#define IDC_ENVELOPE_PIC_1              3101
#define IDC_ENVELOPE_PIC_2              3102
#define IDC_ENVELOPE_PIC_3              3103
#define IDC_ENVELOPE_PIC_4              3104
#define IDC_ENVELOPE_PIC_5              3105
#define IDC_ENVELOPE_PIC_6              3106
#define IDC_ENVELOPE_PIC_7              3107
#define IDC_ENVELOPE_PIC_8              3108
#define IDC_ENVELOPE_PIC_9              3109
#define IDC_TB_FILE                     3110
#define IDC_TB_EDIT                     3111
#define IDC_TB_VIEW                     3112
#define IDC_TB_FORMAT                   3113
#define IDC_TB_TOOLS                    3114
#define IDC_TB_HELP                     3115
#define IDC_DOC_MATCHING_CARD           3116
#define IDC_DOC_PRINT_PREVIEW           3117
#define IDC_CONVERT_TO_JPG              4000
#define IDC_CONVERT_TO_JPG05            4001
#define IDC_CONVERT_TO_JPG20            4004
#define IDC_CONVERT_TO_JPG30            4006
#define IDC_CONVERT_TO_JPG40            4008
#define IDC_CONVERT_TO_JPG50            4010
#define IDC_CONVERT_TO_JPG55            4011
#define IDC_CONVERT_TO_JPG60            4012
#define IDC_CONVERT_TO_JPG65            4013
#define IDC_CONVERT_TO_JPG70            4014
#define IDC_CONVERT_TO_JPG75            4015
#define IDC_CONVERT_TO_JPG80            4016
#define IDC_CONVERT_TO_JPG85            4017
#define IDC_CONVERT_TO_JPG90            4018
#define IDC_CONVERT_TO_JPG95            4019
#define IDC_CHECKFORUPDATES             4024
#define IDC_DOC_LOCALPRINT              4025
#define IDC_SELECTPRINTER_GROUP         4026
#define IDC_VIEW_ZOOM                   4057
#define ID_ZOOM_SELECTION               4061
#define ID_ZOOM_FULL                    4062
#define ID_ZOOM_300                     4063
#define ID_ZOOM_400                     4064
#define ID_ZOOM_500                     4066
#define ID_ZOOM_PAGEWIDTH               4070
#define ID_ZOOM_OUT                     4071
#define ID_ZOOM_IN                      4072
#define ID_VIEW_PAGEWIDTH               4074
#define ID_VIEW_SELECTION               4075
#define ID_ZOOM_100                     4077
#define ID_ZOOM_200                     4078
#define ID_ZOOM_50                      4079
#define ID_ZOOM_33                      4081
#define ID_ZOOM_75                      4082
#define ID_ZOOM_25                      4083
#define ID_VIEW_ZOOMFULL                4085
#define ID_TOOLS_ADD                    4086
#define ID_FORMAT_HORIZONTALTEXTALIGNMENT 4092
#define ID_FORMAT_VERTICALTEXTALIGNMENT 4096
#define ID_FORMAT_TRANSFORM             4110
#define ID_FORMAT_SIZE                  4115
#define IDC_HORZTEXT_RIGHT              4119
#define IDC_HORZTEXT_LEFT               4120
#define IDC_HORZTEXT_CENTER             4121
#define IDC_VERTTEXT_TOP                4123
#define IDC_VERTTEXT_BOTTOM             4124
#define IDC_VERTTEXT_MIDDLE             4126
#define IDC_DOC_FREEROTATE              4137
#define ID_FILE_RECENTFILES             4139
#define ID_FILE_RECENTFILES4140         4140
#define ID_Menu                         4143
#define ID_TOOLS_TESTCONTENTMANAGER     4144
#define ID_TOOLS_TEST                   4145
#define ID_PREV_PAGE                    4146
#define ID_NEXT_PAGE                    4147
#define ID_CLOSE                        4148
#define IDC_COLOR_LINE                  6005
#define IDC_COLOR_3                     6007
#define IDS_CAL_COLOR_1                 6008
#define IDC_TRANS_COLOR_1               6009
#define IDS_CAL_COLOR_2                 6009
#define IDC_TRANS_COLOR_2               6010
#define IDS_CAL_COLOR_3                 6010
#define IDC_TRANS_COLOR_3               6011
#define IDS_LINE_COLOR                  6011
#define IDS_LINE_SIZE                   6012
#define IDS_CAL_TRANS_YEAR              6013
#define IDS_CAL_TRANS_MONTHYEAR         6013
#define IDS_CAL_TRANS_WEEK              6014
#define IDS_CAL_TRANS_DAYS              6015
#define IDS_DOCWIZ_HOLES                6016
#define IDC_ENVELOPE_HELP               6021
#define IDC_DOC_DISPLAYENV              6022
#define IDC_BTN_ENVELOPE                6022
#define IDC_CHECK2                      6026
#define IDC_EMPTY_EDIT                  6027
#define IDC_EMPTY_STATIC                6028
#define IDC_CHECK_PAPERSEARCH           6029
#define IDC_GROUP_RH                    6030
#define IDC_GROUP_RH_ORIENTATION        6031
#define IDC_GROUP_RH_POSITION           6032
#define IDC_TEXT_RH_INSTRUCT            6033
#define IDC_CHECK_RH_PRINT              6034
#define IDC_COMBO_RH_SHAPES             6035
#define IDC_TEXT_RH_SHAPE               6036
#define IDC_EDIT_RH_EDGEDISTANCE        6037
#define IDC_EDIT_RH_HOLESPACING         6038
#define IDC_TEXT_RH_EDGE                6039
#define IDC_TEXT_RH_HOLES               6040
#define IDC_RADIO_RH_VERT               6041
#define IDC_RADIO_RH_HORZ               6042

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        846
#define _APS_NEXT_COMMAND_VALUE         4149
#define _APS_NEXT_CONTROL_VALUE         6043
#define _APS_NEXT_SYMED_VALUE           117
#endif
#endif
