//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pivot.Web.DBService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DBService.DBService")]
    public interface DBService {
        
        // CODEGEN: Generating message contract since element name query from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/GetDeflate", ReplyAction="http://tempuri.org/DBService/GetDeflateResponse")]
        Pivot.Web.DBService.GetDeflateResponse GetDeflate(Pivot.Web.DBService.GetDeflateRequest request);
        
        // CODEGEN: Generating message contract since element name query from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/GetGZip", ReplyAction="http://tempuri.org/DBService/GetGZipResponse")]
        Pivot.Web.DBService.GetGZipResponse GetGZip(Pivot.Web.DBService.GetGZipRequest request);
        
        // CODEGEN: Generating message contract since element name query from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/Get", ReplyAction="http://tempuri.org/DBService/GetResponse")]
        Pivot.Web.DBService.GetResponse Get(Pivot.Web.DBService.GetRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDeflateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDeflate", Namespace="http://tempuri.org/", Order=0)]
        public Pivot.Web.DBService.GetDeflateRequestBody Body;
        
        public GetDeflateRequest() {
        }
        
        public GetDeflateRequest(Pivot.Web.DBService.GetDeflateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDeflateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string query;
        
        public GetDeflateRequestBody() {
        }
        
        public GetDeflateRequestBody(string query) {
            this.query = query;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDeflateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDeflateResponse", Namespace="http://tempuri.org/", Order=0)]
        public Pivot.Web.DBService.GetDeflateResponseBody Body;
        
        public GetDeflateResponse() {
        }
        
        public GetDeflateResponse(Pivot.Web.DBService.GetDeflateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDeflateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDeflateResult;
        
        public GetDeflateResponseBody() {
        }
        
        public GetDeflateResponseBody(string GetDeflateResult) {
            this.GetDeflateResult = GetDeflateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGZipRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGZip", Namespace="http://tempuri.org/", Order=0)]
        public Pivot.Web.DBService.GetGZipRequestBody Body;
        
        public GetGZipRequest() {
        }
        
        public GetGZipRequest(Pivot.Web.DBService.GetGZipRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGZipRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string query;
        
        public GetGZipRequestBody() {
        }
        
        public GetGZipRequestBody(string query) {
            this.query = query;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGZipResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGZipResponse", Namespace="http://tempuri.org/", Order=0)]
        public Pivot.Web.DBService.GetGZipResponseBody Body;
        
        public GetGZipResponse() {
        }
        
        public GetGZipResponse(Pivot.Web.DBService.GetGZipResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGZipResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetGZipResult;
        
        public GetGZipResponseBody() {
        }
        
        public GetGZipResponseBody(string GetGZipResult) {
            this.GetGZipResult = GetGZipResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get", Namespace="http://tempuri.org/", Order=0)]
        public Pivot.Web.DBService.GetRequestBody Body;
        
        public GetRequest() {
        }
        
        public GetRequest(Pivot.Web.DBService.GetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string query;
        
        public GetRequestBody() {
        }
        
        public GetRequestBody(string query) {
            this.query = query;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResponse", Namespace="http://tempuri.org/", Order=0)]
        public Pivot.Web.DBService.GetResponseBody Body;
        
        public GetResponse() {
        }
        
        public GetResponse(Pivot.Web.DBService.GetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetResult;
        
        public GetResponseBody() {
        }
        
        public GetResponseBody(System.Xml.Linq.XElement GetResult) {
            this.GetResult = GetResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DBServiceChannel : Pivot.Web.DBService.DBService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DBServiceClient : System.ServiceModel.ClientBase<Pivot.Web.DBService.DBService>, Pivot.Web.DBService.DBService {
        
        public DBServiceClient() {
        }
        
        public DBServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DBServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Pivot.Web.DBService.GetDeflateResponse Pivot.Web.DBService.DBService.GetDeflate(Pivot.Web.DBService.GetDeflateRequest request) {
            return base.Channel.GetDeflate(request);
        }
        
        public string GetDeflate(string query) {
            Pivot.Web.DBService.GetDeflateRequest inValue = new Pivot.Web.DBService.GetDeflateRequest();
            inValue.Body = new Pivot.Web.DBService.GetDeflateRequestBody();
            inValue.Body.query = query;
            Pivot.Web.DBService.GetDeflateResponse retVal = ((Pivot.Web.DBService.DBService)(this)).GetDeflate(inValue);
            return retVal.Body.GetDeflateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Pivot.Web.DBService.GetGZipResponse Pivot.Web.DBService.DBService.GetGZip(Pivot.Web.DBService.GetGZipRequest request) {
            return base.Channel.GetGZip(request);
        }
        
        public string GetGZip(string query) {
            Pivot.Web.DBService.GetGZipRequest inValue = new Pivot.Web.DBService.GetGZipRequest();
            inValue.Body = new Pivot.Web.DBService.GetGZipRequestBody();
            inValue.Body.query = query;
            Pivot.Web.DBService.GetGZipResponse retVal = ((Pivot.Web.DBService.DBService)(this)).GetGZip(inValue);
            return retVal.Body.GetGZipResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Pivot.Web.DBService.GetResponse Pivot.Web.DBService.DBService.Get(Pivot.Web.DBService.GetRequest request) {
            return base.Channel.Get(request);
        }
        
        public System.Xml.Linq.XElement Get(string query) {
            Pivot.Web.DBService.GetRequest inValue = new Pivot.Web.DBService.GetRequest();
            inValue.Body = new Pivot.Web.DBService.GetRequestBody();
            inValue.Body.query = query;
            Pivot.Web.DBService.GetResponse retVal = ((Pivot.Web.DBService.DBService)(this)).Get(inValue);
            return retVal.Body.GetResult;
        }
    }
}
