##############################################################################
#                                                                            #
#  (C) Copyright 1992 by Micrografx, Inc.  All rights reserved.              #
#                                                                            #
#  This material is confidential and considered a trade secret.              #
#   Permission to use this work for any purpose must by obtained in writing  #
#   from Micrografx Inc., 1303 Arapaho, Richardson, TX. 75081.               #
#                                                                            #
##############################################################################
#                                                                            
##############################################################################
#
#--- What is getting made - this is the name of this 'project'
#
PCHNAME=STDAFX
REFDIR=..\ref
MAKDIR=$(REFDIR)
!IFNDEF PROJ
!IFDEF BUILDDLL
PROJ=appdll
OBJDIR=dllobj
FLAGS=/MT -D_USRDLL
!ELSE
PROJ=apputil
!ENDIF
!ENDIF
DEFAULTBUILD =$(OBJDIR) $(PROJ).lib

PCHDEPEND=\
	cmsutil.h \
	cpo.h \
	getline.h \
	list.h \
 	mask.h \
 	merge.h \
	object.h \
	pixmap.h \
	appdata.h

INSTALLLIST=\
	$(REFDIR)\$(PROJ).lib\
	$(REFDIR)\cmsutil.h \
	$(REFDIR)\cpo.h \
	$(REFDIR)\getline.h \
	$(REFDIR)\list.h \
 	$(REFDIR)\mask.h \
 	$(REFDIR)\merge.h \
	$(REFDIR)\object.h \
	$(REFDIR)\pixmap.h \
	$(REFDIR)\appdata.h
	

##############################################################################
#
#--- insert the standard stuff for applications and/or libs
#
!include "$(MAKDIR)\win.mak"

##############################################################################
#
#--- Interesting files
#
OBJS    =\
	$(OBJDIR)\stdafx.obj\
	$(OBJDIR)\cmsutil.obj \
	$(OBJDIR)\cpo.obj \
	$(OBJDIR)\getline.obj \
	$(OBJDIR)\list.obj \
 	$(OBJDIR)\mask.obj \
 	$(OBJDIR)\merge.obj \
	$(OBJDIR)\object.obj \
	$(OBJDIR)\pixmap.obj \
	$(OBJDIR)\textobj.obj
	

##############################################################################
#
#--- Targets
default: $(DEFAULTBUILD)

$(PROJ).lib: $(OBJS)
  @del $@ >nul
  $(LIBEXE) $(LIBFLAGS) /out:$@ @<<
$(OBJS)
<<

##############################################################################
#
#--- Implicit Rules
#    make any you think you will need.  They can be identical in nature,
#    but NMAKE wants have at least one for each possible virtual combination
#
##############################################################################
    
