#pragma once

// Replace the greetings form fields
static const LPCSTR FieldArray[] = {
//	"AddAPhoto",									"AddAPhoto",
	"Address",										"Address",
	"Age",											"Age",
	"Animal Type",									"Animal",
	"Attendant's Name",								"Attendname",
	"Name Of Author",								"Author",
	"Baby's Name",									"Babyname",
	"Date Of Birth",								"Birthdate",
	"Time Of Birth",								"Birthtime",
	"Book Title",									"Booktitle",
	"Breed",										"Breed",
	"Bride's Name",									"Bride",
	"Brother Or Sister",							"BroorSis",
	"Brother",										"Brother",
	"Add a Caption",								"Caption",
	"Church Name",									"Churchname",
	"City/State",									"Citystate",
	"Closing,",										"Closing",
	"Name Of Conflict",								"Conflict",
	"Reason For Congratulations",					"Congrtrsn",
	"Couple's Name",								"Couplename",
	"Current Year",									"Curryear",
	"Dad's Name",									"Dadname",
	"Date",											"Date",
	"Date And Time",								"Datetime",
	"Deceased's Name",								"Decname",
	"Dog's Name",									"Dogname",
	"Type Date Of Event",							"Enterdate",
	"Type Time Of Event",							"Entertime",
	"Event",										"Event",
//	"Font Color",									"FCOLOR",
//	"Font Family",									"FFAMILY",
//	"Font Size",									"FSIZE",
//	"Font Style",									"FSTYLE",
//	"Font Weight",									"FWEIGHT",
	"Favorite Beverage",							"Favbevrg",
	"Favorite Food",								"Favfood",
	"Recipient's Favorite Sport",					"Favsport",
	"Gift",											"Flooz",
	"First Recipient",								"Frfirstnam",
	"" /*"Sender's Name"*/,							"From",
//	"Gift Membership Redemption Code",				"Giftrcode",
	"Grandparent's Name",							"Gndprtname",
	"Graduate's Name",								"Gradname",
	"Name for Grandmother",							"Grndmaname",
	"Name for Grandfather",							"Grndpaname",
	"Groom's Name",									"Groomsname",
	"Guest Of Honor",								"Guestname",
	"He Or She",									"Heorshe",
	"Her Name",										"Hername",
	"His Or Her",									"Himorher",
	"Him Or Her",									"Himorher",
	"His Name",										"Hisname",
	"Host's Name",									"Hostname",
	"I Or We",										"Iorwe",
	"Child's name",									"Kidname",
	"Length",										"Length",
	"Location",										"Location",
	"Male Or Female",								"Malefemale",
//	"Type Mambo Mail Line 1",						"Mamboline1",
//	"Type Mambo Mail Line 2",						"Mamboline2",
//	"Type Mambo Mail Line 3",						"Mamboline3",
	"Me Or Us",										"Meorus",
	"Mine Or Ours",									"Mineorours",
	"Mom's Name",									"Momname",
	"Mom Or Dad",									"Momordad",
	"Mother To Be's Name",							"Mothertobe",
	"Message",										"Msg",
	"Message",										"MsgDpDown",
//	"Deck The Halls|Nutcracker|",					"Music1",
	"My Or Our",									"Myorours",
//	"NETA",											"NETA",
	"New Phone Number",								"NewPhone",
	"New Address",									"Newaddress",
	"Occasion",										"Occasion",
	"Newspaper Name",								"Papername",
	"Parent's Name",								"Parentname",
	"Pet's Name",									"Petsname",
	"Phone Number",									"Phonenbr",
	"Your Poem Here",								"Poem",
	"Reply Requested",								"RR",
	"Recipient's Activity",							"Ractivity",
	"Body Part",									"Rbodypart",
	"Type Of Car",									"Rcarmake",
	"City Or Town",									"Rcity",
	"Recipient's Dislikes",							"Rdislikes",
	"Recipient's Company",							"Receiverco",
	"Registry Location",							"Reglocatn",
	"Recipient's Eye Color",						"Reyecolor",
	"" /*"Recipient's First Name"*/,				"Rfirstname",
	"Recipient's Full Name",						"Rfullname",
	"Recipient's Initial",							"Rin",
	"Recipient's Initial",							"Rinit",
	"Recipient's Last Name",						"Rlastname",
	"Recipient's Likes",							"Rlikes",
	"Recipient's Pet's Name",						"Rpetname",
	"Recipient's Quote",							"Rquote",
	"Relationship",									"Rrelation",
	"Recipient's Sports Team",						"Rsprtsteam",
	"State",										"Rstate",
	"RsvpInformation",								"Rsvp",
	"Sender Activity",								"Sactivity",
	"Name Of School",								"School",
	"School Or Grade",								"Schoolname",
	"School Name",									"Schoolname",
	"City Or Town",									"Scity",
	"Sender's Company",								"Scompany",
	"Sender's Dislikes",							"Sdislikes",
	"Season",										"Season",
	"Sender Email",									"Semail",
	"Sender",										"Sender",
	"Sender's Organization",						"Senderco",
//	"Series Card Initial Message",					"SeriIniMsg",
//	"Series Sequence Number",						"SeriSeqNum",
//	"Sender's Initial",								"Sin",
//	"Sender's Initial",								"Sinit",
	"SisterInLaw",									"SisInLaw",
	"Sender's Last Name",							"Slastname",
	"Sender's Likes",								"Slikes",
	"Sender's Quote",								"Squote",
	"Relationship",									"Srelation",
	"Second Recipient",								"Srfirstnam",
	"Sender's Sports Team",							"Ssprtsteam",
	"Store Name",									"Storename",
	"Student Name",									"Studentnam",
	"Time",											"Time",
	"Weight",										"Weight",
	"Years together",								"Years",
	"Photo Album Title",							"altitle",
	"Brother Or Sister's Name",						"brosisname",
	"Cell Number",									"cellnum",
	"From",											"from",
	"HeShe Or They",								"heshethey",
	"Naughty People",								"naughty",
	"New Address",									"newaddress",
	"New Phone Number",								"newphone",
	"Nice People",									"nicepeople",
//	"Photo Caption 10",								"pcaption10",
//	"Photo Caption 4",								"pcaption4",
//	"Photo Caption 5",								"pcaption5",
//	"Photo Caption 6",								"pcaption6",
//	"Photo Caption 7",								"pcaption7",
//	"Photo Caption 8",								"pcaption8",
//	"Photo Caption 9",								"pcaption9",
//	"Photo Captions",								"pcaptions",
	"Person's Name",								"personname",
//	"Photo 10",										"photo10",
//	"Photo 4",										"photo4",
//	"Photo 5",										"photo5",
//	"Photo 6",										"photo6",
//	"Photo 7",										"photo7",
//	"Photo 8",										"photo8",
//	"Photo 9",										"photo9",
//	"Photos",										"photos",
//	"Product Line",									"producline",
//	"Redemption Expiration Date",					"redexpdate",
	"My Text Message Address",						"textadd",
	"URL Name",										"urlname",

	"" /*"Recipient's Name"*/,						"NameFirstTo",
	"" /*"Sender's Name"*/,							"NameFirstFrom",
	"Host's Name",									"Hosted By",
};
