//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AgOutlookAddIn.rc
//
#define IDR_ADDIN                       1
#define IDR_OEADDIN                     2
#define IDR_DIALOGMENU                  100
#define IDR_OPTIONSMENU                 101
#define IDR_CONTENTMENU                 102
#define IDR_JMEXPLORERBAND              104
#define IDR_PREVIEW_MENU1               105
#define IDR_PREVIEW_MENU2               106
#define IDR_JMTOOLBAND                  107
#define IDR_BROWSERHELPEROBJ            108
#define IDR_OPTIONS_MENU2               111
#define IDR_UPDATEOBJ                   113
#define IDB_AOLADDIN                    114
#define IDR_AOLADDIN                    115
#define IDS_MANIFEST_URL                199
#define IDS_PROJNAME                    200
#define IDS_ECARD_SITE1                 201
#define IDS_ECARD_SITE2                 202
#define IDS_ECARD_SITE3                 203
#define IDS_ECARD_SITE4                 204
#define IDS_ECARD_URL1                  221
#define IDS_ECARD_URL2                  222
#define IDS_ECARD_URL3                  223
#define IDS_ECARD_URL4                  224
#define IDS_GAMES_URL                   230
#define IDI_LOGO                        231
#define IDD_MESSAGE_DIALOG              237
#define IDB_AG_16                       253
#define IDB_BLUE_16                     254
#define IDB_BEATGREETS_16               255
#define IDB_EGREETS_16                  256
#define IDD_ECARD_DIALOG                257
#define IDD_ABOUTBOX                    300
#define IDD_HTMLMENU                    301
#define IDS_BTN1                        301
#define IDD_HTMLDIALOG                  302
#define IDS_BTN2                        302
#define IDS_BTN3                        303
#define IDD_PREVIEWDIALOG               304
#define IDS_BTN4                        304
#define IDS_BTN5                        305
#define IDS_BTN6                        306
#define IDS_BTN7                        307
#define IDS_BTN8                        308
#define IDS_BTN9                        309
#define IDS_BTN10                       310
#define IDS_BTN11                       311
#define IDS_BTN1_TIP                    401
#define IDS_BTN2_TIP                    402
#define IDS_BTN3_TIP                    403
#define IDC_EXPLORER                    404
#define IDS_BTN4_TIP                    404
#define IDS_BTN5_TIP                    405
#define IDS_BTN6_TIP                    406
#define IDS_BTN7_TIP                    407
#define IDC_MSG_TEXT                    408
#define IDS_BTN8_TIP                    408
#define IDC_STATIC_LOGO                 409
#define IDS_BTN9_TIP                    409
#define IDS_BTN10_TIP                   410
#define IDS_BTN11_TIP                   411
#define IDC_ECARD_LIST                  457
#define IDS_YAHOO_FRAMEID_01            500
#define IDB_BTN1                        501
#define IDS_HOTMAIL_FRAMEID_01          501
#define IDB_BTN2                        502
#define IDS_HOTMAIL_FRAMEID_02          502
#define IDB_BTN3                        503
#define IDS_YAHOO_COMPOSE_MARK          503
#define IDS_YAHOO_SEND_MARK_01          504
#define IDB_BTN4                        504
#define IDB_BTN5                        505
#define IDS_YAHOO_SEND_MARK_02          505
#define IDB_BTN6                        506
#define IDS_HOTMAIL_SEND_MARK_01        506
#define IDB_BTN7                        507
#define IDS_YAHOO_FRAMEID_01_ver2       507
#define IDB_BTN8                        508
#define IDS_YAHOO_FRAMEID_02_ver2       508
#define IDB_BTN9                        509
#define IDB_BTN10                       510
#define IDB_BTN11                       511
#define IDS_FAQ_GENERAL_URL             601
#define IDS_FAQ_HOTMAIL_URL             602
#define IDS_FAQ_YAHOO_URL               603
#define ID_OPTIONS_SIGNIN               700
#define ID_OPTIONS_CHECKFORUPDATES      701
#define ID_OPTIONS_REFERAFRIEND         705
#define ID_OPTIONS_ABOUTJAZZYMAIL       712
#define ID_OPTIONS_HELPCENTER           714
#define ID_CONTENT_SEND                 715
#define ID_CONTENT_PREVIEW              716
#define ID_CONTENT_ADDTOFAVORITES       717
#define ID_CONTENT_SETDEFAULT           720
#define ID_PREV_CLOSE                   722
#define ID_OPTIONS_SHOWTRAYICON         726
#define ID_OPTIONS_GIVEFEEDBACK         727
#define ID_OPTIONS_UPGRADENOW           731
#define ID_OPTIONS_MYACCOUNT            732
#define ID_OPTIONS_JAZZYMAILHOME        733
#define ID_FILE_SMARTCACHE              734
#define ID_OPTIONS_CLEARSTATIONERY      735
#define ID_OPTIONS_CLEARDEFAULTSTATIONERY 737
#define ID_CONTENT_COMPOSENEW           741
#define ID_OPTIONS_OPTIMIZE             744
#define ID_OPTIONS_SETTINGS             745
#define ID_Menu                         751
#define ID_ECARDS_BLUEMOUNTAIN          752
#define ID_ECARDS_AMERICANGREETINGS     753
#define ID_ECARDS_EGREETINGS            756
#define ID_ECARDS_BEATGREETS            757
#define IDH_TRAILER                     800
#define IDS_SECURITY_ACTIVEX_FAIL       801
#define IDS_MANIFEST_ERROR              802
#define IDS_OPTIONS_ERROR               803
#define IDS_ADDAPHOTO_ERROR             804
#define IDS_WORD_PROMPT                 900
#define IDS_ACTIVEX_PROMPT              901
#define IDS_FLASH_PROMPT                902
#define IDS_UPGRADE_PROMPT              903
#define IDS_NEWVERSION_PROMPT           905
#define IDS_CURRENTVERSION_PROMPT       906
#define IDS_VERSIONUPDATED_PROMPT       907
#define IDS_AUTOUPDATE_ONLINE_PROMPT    908
#define IDS_IMAGE_SERVER                909
#define IDS_TRAILER_NAME                910
#define IDS_SENDPICTURES_PROMPT         911
#define IDS_ADDAPHOTO_INFO_PROMPT       912
#define IDS_HOTMAIL_RTE_WARN            1001
#define IDS_YAHOO_CG_WARN               1002
#define IDS_MSN_RTE_WARN                1003
#define IDS_GENERAL_WARN                1004
#define IDS_REFERFRIEND_WARN            1005
#define IDS_BROWSEREXT_WARN             1006
#define IDS_AOL_COMPOSE_WARN            1007

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        258
#define _APS_NEXT_COMMAND_VALUE         758
#define _APS_NEXT_CONTROL_VALUE         459
#define _APS_NEXT_SYMED_VALUE           116
#endif
#endif
