//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by JMSrvr.rc
//
#define VS_VERSION_INFO                 1
#define IDI_LOGO                        2
#define IDI_LOGO16                      3
#define IDC_BACK                        3
#define IDC_NEXT                        4
#define IDC_DONE                        5
#define ID_HAND                         10
#define IDR_JMSRVR                      101
#define IDR_JMBRKR                      102
#define IDR_POPUP_MENU                  103
#define IDD_OPTIMIZEDLG                 110
#define IDD_ABOUTBOX                    201
#define IDD_REGISTERDIALOG              202
#define IDR_POPUP_MENU2                 203
#define IDD_GENERAL_PROPPAGE            238
#define IDD_PREFERENCE_PROPPAGE         240
#define IDD_EMAIL_PROPPAGE              241
#define IDD_MAINT_PROPPAGE              241
#define IDD_ABOUT2                      242
#define IDC_EXPLORER1                   301
#define IDC_ALWAYSONTOP_CHECK           303
#define IDC_PREFERENCES_STATIC          304
#define IDD_OPTIMIZEDLG_INTRO           305
#define IDD_OPTIMIZEDLG_STEP1           306
#define IDD_OPTIMIZEDLG_FINAL           307
#define IDD_OPTIMIZEDLG_CANCEL          308
#define IDC_DEFAULTSTATIONERY_STATIC    309
#define IDC_EXPRESS_USEDEFAULT_CHECK    310
#define IDC_IE_USEDEFAULT_CHECK         311
#define IDC_LICENSE_STATIC              314
#define IDC_TERMOFSALES_STATIC          315
#define IDC_TERMSOFSERVICE_STATIC       315
#define IDC_PRIVACY_STATIC              316
#define IDC_VERSION_STATIC              317
#define IDC_IECAT_COMBO                 328
#define IDC_IECAT_STATIC                329
#define IDC_IE_STATIC                   330
#define IDC_MISC_STATIC                 331
#define IDC_HOME_STATIC                 332
#define IDC_OL_CLEAR_BUTTON             333
#define IDC_OE_CLEAR_BUTTON             334
#define IDC_IE_CLEAR_BUTTON             335
#define IDC_AOL_CHECK                   336
#define IDC_AOL_CLEAR_BUTTON            338
#define ID_HELP_FEEDBACK                401
#define ID_HELP_FAQ                     402
#define ID_HELP_TOPICS                  403
#define ID_TRAY_NEWEMAIL                404
#define ID_TRAY_UPGRADENOW              405
#define ID_TRAY_MYACCOUNT               406
#define ID_TRAY_HELP                    407
#define ID_TRAY_HOME                    408
#define ID_TRAY_HIDE                    409
#define ID_TRAY_ABOUT                   410
#define IDC_OPTIMIZE_OUTLOOK            411
#define ID_TRAY_SETTINGS                411
#define IDC_OPTIMIZE_OE                 412
#define IDC_STATIC_UNREGISTERED         412
#define IDC_OPTIMIZE_IE                 413
#define ID_TRAY_REFERAFRIEND            413
#define IDC_OUTLOOK_CHECK               415
#define IDC_CLEARDEFAULT                415
#define ID_TRAY_FEEDBACK                415
#define IDC_TRAYICON_CHECK              416
#define IDC_OTLK_USEDEFAULT_CHECK2      417
#define IDC_OTLK_USEDEFAULT_CHECK       417
#define ID_TRAY_LAUNCH                  418
#define IDC_SMARTCACHE_CHECK            419
#define IDC_MYACCOUNT_BTN               420
#define IDC_UNLOCK_BTN                  421
#define IDC_ACCOUNT_STATIC              422
#define IDC_ACCOUNT_STATIC1             423
#define IDC_UNLOCK_STATIC               424
#define IDC_PREFERENCE_STATIC           425
#define IDC_CHECKUPDATES_BTN            426
#define IDC_UPDATES_STATIC              427
#define IDC_OPTIMIZE_BTN                428
#define IDC_OPTIMIZE_STATIC             429
#define IDC_CLEARCURRENT                430
#define IDC_AOL_USEDEFAULT_CHECK        430
#define IDC_EMAILADDRESS                431
#define IDC_EMAILADDRESS_STATIC         431
#define IDC_EMAIL_STATIC                432
#define IDC_REGISTEREDEMAIL             434
#define IDC_ACTIVEMAIL_STATIC           438
#define IDC_EXPRESS_CHECK               439
#define IDC_WEBMAIL_CHECK               440
#define IDC_PROMO_CHECK                 442
#define IDC_REFERAFRIEND_BUTTON         443
#define IDC_REFERAFRIEND_STATIC         444
#define IDC_STATIONERY_STATIC           445
#define IDC_FEEDBACK_BUTTON             446
#define IDC_FEEDBACK_STATIC             447
#define IDC_HELP_BUTTON                 448
#define IDC_HELP_STATIC                 449
#define IDC_ABOUT_STATIC                450
#define IDC_MAILSELECT_STATIC           454
#define IDB_BTN1                        500
#define IDS_PROJNAME                    501
#define IDB_BTN2                        501
#define IDS_REG_PROMPT                  502
#define IDB_BTN3                        502
#define IDS_REG_TITLE                   503
#define IDB_BTN4                        503
#define IDS_REG_UPGRADE_SUCCESS         504
#define IDB_BTN5                        504
#define IDS_REG_UPGRADE_FAIL            505
#define IDB_BTN6                        505
#define IDS_REG_UNLOCK_SUCCESS          506
#define IDB_BTN7                        506
#define IDS_REG_UNLOCK_FAIL             507
#define IDB_BTN8                        507
#define IDS_SECURITY_SUBMIT_FAIL        508
#define IDB_BTN9                        508
#define IDS_NEWCLIENTS_PROMPT           509
#define IDB_BTN10                       509
#define IDS_IEDISABLE                   510
#define IDS_IEDISABLE_PROMPT            510
#define IDS_AOLDISABLE_PROMPT2          511
#define IDS_AOLDISABLE_PROMPT           511
#define IDS_LICENSE_URL                 600
#define IDS_SALES_URL                   601
#define IDS_SERVICES_URL                601
#define IDS_PRIVACY_URL                 602
#define IDS_SMARTCACHE_TIP              700
#define IDS_TRAYICON_CHECK              701
#define IDS_TRAYICON_TIP                701
#define IDS_CMENABLE_TIP                702
#define IDS_IEONLY_TIP                  703
#define IDS_DEFSTA_TIP                  704
#define IDS_ALWAYSONTOP_TIP             705
#define IDS_REGEMAIL_TIP                706
#define IDS_UNLOCK_TIP                  707
#define IDS_MYACCOUNT_TIP               708
#define IDS_PROMO_TIP                   709
#define IDS_CHECKUPDATES_TIP            710
#define IDS_OPTIMIZE_TIP                711
#define IDS_CLEARSTA                    712
#define IDS_CLEARSTA_TIP                712
#define IDS_WORD_PROMPT                 900
#define IDS_ACTIVEX_PROMPT              901
#define IDS_FLASH_PROMPT                902
#define IDS_SENDPICTURES_PROMPT         903
#define IDS_BROWSEREXT_WARN             1006

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        205
#define _APS_NEXT_COMMAND_VALUE         419
#define _APS_NEXT_CONTROL_VALUE         339
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
