#pragma once

template <class T>
class CProxy_ITextEditorEvents : public IConnectionPointImpl<T, &__uuidof(_ITextEditorEvents), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
