##############################################################################
#                                                                            #
#  (C) Copyright 1992 by Micrografx, Inc.  All rights reserved.              #
#                                                                            #
#  This material is confidential and considered a trade secret.              #
#   Permission to use this work for any purpose must by obtained in writing  #
#   from Micrografx Inc., 1303 Arapaho, Richardson, TX. 75081.               #
#                                                                            #
##############################################################################
#                                                                            #
#                     MGX standard makefile insert               	          #
#                                                                            #
##############################################################################
#
#            Instructions:
# You should do the following before making:
#
#   1) Set the PROJ variable to what you are calling your project.
#   2) Set up any Non-Project Information
#   3) set up the 'interesting' file and targets
#
##############################################################################
#
#--- What is getting made - this is the name of this 'project'
#
REFDIR=..\ref
MAKDIR=.
DSTDIR=..\dst
DEFAULTBUILD=
INSTALLLIST=\
	$(REFDIR)\win.mak\
	$(REFDIR)\win16.mak\
	$(REFDIR)\BASETYPE.H\
	$(REFDIR)\FXPARMS.H\
	$(REFDIR)\PCDLIB.H\
	$(REFDIR)\TYPES.H\
	$(REFDIR)\PITYPES.H\
	$(REFDIR)\PIGENERA.H\
	$(REFDIR)\PIFILTER.H\
	$(REFDIR)\PIEXPORT.H\
	$(REFDIR)\MSVIDEO.LIB\
	$(REFDIR)\PCDLIB.LIB

##############################################################################
#
#--- insert the standard stuff for applications and/or libs
#
!include <win.mak>

