##############################################################################
#                                                                            #
#  (C) Copyright 1992 by Micrografx, Inc.  All rights reserved.              #
#                                                                            #
#  This material is confidential and considered a trade secret.              #
#   Permission to use this work for any purpose must by obtained in writing  #
#   from Micrografx Inc., 1303 Arapaho, Richardson, TX. 75081.               #
#                                                                            #
##############################################################################
#
#--- What is getting made - this is the name of this 'project'
#
NOPCH=
REFDIR=..\ref
MAKDIR=$(REFDIR)
!IFNDEF PROJ
PROJ=browser
!ENDIF
DEFAULTBUILD =$(OBJDIR) $(PROJ).lib
PROJFLAGS=-I..\pp\inc
INSTALLLIST=\
	$(REFDIR)\$(PROJ).lib\
	$(REFDIR)\browser.h\
	$(REFDIR)\extbsr.h\
	$(REFDIR)\bsrutil.h\
	$(REFDIR)\bsrtypes.h\
	$(REFDIR)\bsrid.h

##############################################################################
#
#--- insert the standard stuff for applications and/or libs
#
!include "$(MAKDIR)\win.mak"

##############################################################################
#
#--- Interesting files
#
ASMOBJS =\

OBJS    =\
	$(OBJDIR)\cthmmgr.obj \
	$(OBJDIR)\dbfmgr.obj \
	$(OBJDIR)\browser.obj \
	$(OBJDIR)\extbsr.obj \
    	$(OBJDIR)\bsrport.obj \
	$(OBJDIR)\bsrdlgs.obj \
	$(OBJDIR)\bsritems.obj \
	$(OBJDIR)\bsrutil.obj \
	$(OBJDIR)\bsrcom.obj \
	$(OBJDIR)\handlebs.obj \
	$(OBJDIR)\oldthm.obj\
	$(OBJDIR)\search.obj \
	$(OBJDIR)\thmbsr.obj \
	$(OBJDIR)\thmmgr.obj

##############################################################################
#
#--- Targets
$(PROJ).lib: $(OBJS)
  @del $@ >nul
  $(LIBEXE) $(LIBFLAGS) /out:$@ @<<
$(OBJS)
<<

##############################################################################
#
#--- Implicit Rules
#    make any you think you will need.  They can be identical in nature,
#    but NMAKE wants have at least one for each possible virtual combination
#

##############################################################################
#
#--- Dependencies
#
##############################################################################




