// include file for raddon.c

// defines for GetAppFunction function ID's
// this MUST match the header defines in the DLL's
#define A_IMAGE_LOAD		1
#define A_DLGEND			2
#define T_TIFRDR			3
#define F_FTOBMP			4
#define F_FDEPTH			5
#define F_FGETRGB			6
#define F_FPOINTER			7
#define F_FXSIZE			8
#define F_FYSIZE			9
#define F_FCLOSE			10
#define I_GETBASE			11
#define I_GETBASEEDITF		12
#define I_GETNEXTOBJ		13
#define I_ADDNEWOBJ			14
#define I_COMBINEOBJ		15
#define I_DELETEOBJS		16
#define I_SETPIXELPROC		17
#define	I_CHANGESEL			18
#define	I_ADJUSTLSO			19
#define	I_FINDOBJ			20
#define AN_ANIMATEPROC		21
#define R_GOROOM			22
#define R_GOPAINT			23
#define	M_MASKCLOSE			24
#define	M_MASKCREATE		25
#define	M_MASKCREATEALPHAF	26
#define O_CREATEFF			27
#define	O_OBJUNLINK			28
#define	P_PIXMAPFRAME		29
#define	F_ATOWINRECT		30
#define A_STARTANI			31
#define A_STOPANI			32
#define	S_SOUNDSTARTRES		33
#define	S_SOUNDSTARTFILE	34
#define	S_SOUNDSTOP			35
#define S_SOUNDSTOPFREE		36
#define S_MIXSOUNDSTARTRES	37
#define S_MIXSOUNDSTARTFILE	38
#define	S_MIXSOUNDSTOPALL	39
#define	F_FSETRGB			40
#define T_TIFFRES2FRAME		41
#define I_DELETEOBJ			42

