//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace Money.DBService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DBService.DBService")]
    public interface DBService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/DBService/GetDeflate", ReplyAction="http://tempuri.org/DBService/GetDeflateResponse")]
        System.IAsyncResult BeginGetDeflate(Money.DBService.GetDeflateRequest request, System.AsyncCallback callback, object asyncState);
        
        Money.DBService.GetDeflateResponse EndGetDeflate(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/DBService/GetGZip", ReplyAction="http://tempuri.org/DBService/GetGZipResponse")]
        System.IAsyncResult BeginGetGZip(Money.DBService.GetGZipRequest request, System.AsyncCallback callback, object asyncState);
        
        Money.DBService.GetGZipResponse EndGetGZip(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/DBService/Get", ReplyAction="http://tempuri.org/DBService/GetResponse")]
        System.IAsyncResult BeginGet(Money.DBService.GetRequest request, System.AsyncCallback callback, object asyncState);
        
        Money.DBService.GetResponse EndGet(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/DBService/GetSchema", ReplyAction="http://tempuri.org/DBService/GetSchemaResponse")]
        System.IAsyncResult BeginGetSchema(Money.DBService.GetSchemaRequest request, System.AsyncCallback callback, object asyncState);
        
        Money.DBService.GetSchemaResponse EndGetSchema(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDeflateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDeflate", Namespace="http://tempuri.org/", Order=0)]
        public Money.DBService.GetDeflateRequestBody Body;
        
        public GetDeflateRequest() {
        }
        
        public GetDeflateRequest(Money.DBService.GetDeflateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDeflateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string query;
        
        public GetDeflateRequestBody() {
        }
        
        public GetDeflateRequestBody(string query) {
            this.query = query;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDeflateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDeflateResponse", Namespace="http://tempuri.org/", Order=0)]
        public Money.DBService.GetDeflateResponseBody Body;
        
        public GetDeflateResponse() {
        }
        
        public GetDeflateResponse(Money.DBService.GetDeflateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDeflateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDeflateResult;
        
        public GetDeflateResponseBody() {
        }
        
        public GetDeflateResponseBody(string GetDeflateResult) {
            this.GetDeflateResult = GetDeflateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGZipRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGZip", Namespace="http://tempuri.org/", Order=0)]
        public Money.DBService.GetGZipRequestBody Body;
        
        public GetGZipRequest() {
        }
        
        public GetGZipRequest(Money.DBService.GetGZipRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGZipRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string query;
        
        public GetGZipRequestBody() {
        }
        
        public GetGZipRequestBody(string query) {
            this.query = query;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGZipResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGZipResponse", Namespace="http://tempuri.org/", Order=0)]
        public Money.DBService.GetGZipResponseBody Body;
        
        public GetGZipResponse() {
        }
        
        public GetGZipResponse(Money.DBService.GetGZipResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGZipResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetGZipResult;
        
        public GetGZipResponseBody() {
        }
        
        public GetGZipResponseBody(string GetGZipResult) {
            this.GetGZipResult = GetGZipResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get", Namespace="http://tempuri.org/", Order=0)]
        public Money.DBService.GetRequestBody Body;
        
        public GetRequest() {
        }
        
        public GetRequest(Money.DBService.GetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string query;
        
        public GetRequestBody() {
        }
        
        public GetRequestBody(string query) {
            this.query = query;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResponse", Namespace="http://tempuri.org/", Order=0)]
        public Money.DBService.GetResponseBody Body;
        
        public GetResponse() {
        }
        
        public GetResponse(Money.DBService.GetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetResult;
        
        public GetResponseBody() {
        }
        
        public GetResponseBody(System.Xml.Linq.XElement GetResult) {
            this.GetResult = GetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSchemaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSchema", Namespace="http://tempuri.org/", Order=0)]
        public Money.DBService.GetSchemaRequestBody Body;
        
        public GetSchemaRequest() {
        }
        
        public GetSchemaRequest(Money.DBService.GetSchemaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetSchemaRequestBody {
        
        public GetSchemaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSchemaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSchemaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Money.DBService.GetSchemaResponseBody Body;
        
        public GetSchemaResponse() {
        }
        
        public GetSchemaResponse(Money.DBService.GetSchemaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSchemaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSchemaResult;
        
        public GetSchemaResponseBody() {
        }
        
        public GetSchemaResponseBody(string GetSchemaResult) {
            this.GetSchemaResult = GetSchemaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DBServiceChannel : Money.DBService.DBService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDeflateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDeflateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetGZipCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetGZipCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Xml.Linq.XElement Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Xml.Linq.XElement)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSchemaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSchemaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DBServiceClient : System.ServiceModel.ClientBase<Money.DBService.DBService>, Money.DBService.DBService {
        
        private BeginOperationDelegate onBeginGetDeflateDelegate;
        
        private EndOperationDelegate onEndGetDeflateDelegate;
        
        private System.Threading.SendOrPostCallback onGetDeflateCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetGZipDelegate;
        
        private EndOperationDelegate onEndGetGZipDelegate;
        
        private System.Threading.SendOrPostCallback onGetGZipCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetDelegate;
        
        private EndOperationDelegate onEndGetDelegate;
        
        private System.Threading.SendOrPostCallback onGetCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetSchemaDelegate;
        
        private EndOperationDelegate onEndGetSchemaDelegate;
        
        private System.Threading.SendOrPostCallback onGetSchemaCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public DBServiceClient() {
        }
        
        public DBServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DBServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetDeflateCompletedEventArgs> GetDeflateCompleted;
        
        public event System.EventHandler<GetGZipCompletedEventArgs> GetGZipCompleted;
        
        public event System.EventHandler<GetCompletedEventArgs> GetCompleted;
        
        public event System.EventHandler<GetSchemaCompletedEventArgs> GetSchemaCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Money.DBService.DBService.BeginGetDeflate(Money.DBService.GetDeflateRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetDeflate(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetDeflate(string query, System.AsyncCallback callback, object asyncState) {
            Money.DBService.GetDeflateRequest inValue = new Money.DBService.GetDeflateRequest();
            inValue.Body = new Money.DBService.GetDeflateRequestBody();
            inValue.Body.query = query;
            return ((Money.DBService.DBService)(this)).BeginGetDeflate(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Money.DBService.GetDeflateResponse Money.DBService.DBService.EndGetDeflate(System.IAsyncResult result) {
            return base.Channel.EndGetDeflate(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetDeflate(System.IAsyncResult result) {
            Money.DBService.GetDeflateResponse retVal = ((Money.DBService.DBService)(this)).EndGetDeflate(result);
            return retVal.Body.GetDeflateResult;
        }
        
        private System.IAsyncResult OnBeginGetDeflate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string query = ((string)(inValues[0]));
            return this.BeginGetDeflate(query, callback, asyncState);
        }
        
        private object[] OnEndGetDeflate(System.IAsyncResult result) {
            string retVal = this.EndGetDeflate(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDeflateCompleted(object state) {
            if ((this.GetDeflateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDeflateCompleted(this, new GetDeflateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDeflateAsync(string query) {
            this.GetDeflateAsync(query, null);
        }
        
        public void GetDeflateAsync(string query, object userState) {
            if ((this.onBeginGetDeflateDelegate == null)) {
                this.onBeginGetDeflateDelegate = new BeginOperationDelegate(this.OnBeginGetDeflate);
            }
            if ((this.onEndGetDeflateDelegate == null)) {
                this.onEndGetDeflateDelegate = new EndOperationDelegate(this.OnEndGetDeflate);
            }
            if ((this.onGetDeflateCompletedDelegate == null)) {
                this.onGetDeflateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDeflateCompleted);
            }
            base.InvokeAsync(this.onBeginGetDeflateDelegate, new object[] {
                        query}, this.onEndGetDeflateDelegate, this.onGetDeflateCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Money.DBService.DBService.BeginGetGZip(Money.DBService.GetGZipRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetGZip(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetGZip(string query, System.AsyncCallback callback, object asyncState) {
            Money.DBService.GetGZipRequest inValue = new Money.DBService.GetGZipRequest();
            inValue.Body = new Money.DBService.GetGZipRequestBody();
            inValue.Body.query = query;
            return ((Money.DBService.DBService)(this)).BeginGetGZip(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Money.DBService.GetGZipResponse Money.DBService.DBService.EndGetGZip(System.IAsyncResult result) {
            return base.Channel.EndGetGZip(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetGZip(System.IAsyncResult result) {
            Money.DBService.GetGZipResponse retVal = ((Money.DBService.DBService)(this)).EndGetGZip(result);
            return retVal.Body.GetGZipResult;
        }
        
        private System.IAsyncResult OnBeginGetGZip(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string query = ((string)(inValues[0]));
            return this.BeginGetGZip(query, callback, asyncState);
        }
        
        private object[] OnEndGetGZip(System.IAsyncResult result) {
            string retVal = this.EndGetGZip(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetGZipCompleted(object state) {
            if ((this.GetGZipCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetGZipCompleted(this, new GetGZipCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetGZipAsync(string query) {
            this.GetGZipAsync(query, null);
        }
        
        public void GetGZipAsync(string query, object userState) {
            if ((this.onBeginGetGZipDelegate == null)) {
                this.onBeginGetGZipDelegate = new BeginOperationDelegate(this.OnBeginGetGZip);
            }
            if ((this.onEndGetGZipDelegate == null)) {
                this.onEndGetGZipDelegate = new EndOperationDelegate(this.OnEndGetGZip);
            }
            if ((this.onGetGZipCompletedDelegate == null)) {
                this.onGetGZipCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetGZipCompleted);
            }
            base.InvokeAsync(this.onBeginGetGZipDelegate, new object[] {
                        query}, this.onEndGetGZipDelegate, this.onGetGZipCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Money.DBService.DBService.BeginGet(Money.DBService.GetRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGet(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGet(string query, System.AsyncCallback callback, object asyncState) {
            Money.DBService.GetRequest inValue = new Money.DBService.GetRequest();
            inValue.Body = new Money.DBService.GetRequestBody();
            inValue.Body.query = query;
            return ((Money.DBService.DBService)(this)).BeginGet(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Money.DBService.GetResponse Money.DBService.DBService.EndGet(System.IAsyncResult result) {
            return base.Channel.EndGet(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.Xml.Linq.XElement EndGet(System.IAsyncResult result) {
            Money.DBService.GetResponse retVal = ((Money.DBService.DBService)(this)).EndGet(result);
            return retVal.Body.GetResult;
        }
        
        private System.IAsyncResult OnBeginGet(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string query = ((string)(inValues[0]));
            return this.BeginGet(query, callback, asyncState);
        }
        
        private object[] OnEndGet(System.IAsyncResult result) {
            System.Xml.Linq.XElement retVal = this.EndGet(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCompleted(object state) {
            if ((this.GetCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCompleted(this, new GetCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAsync(string query) {
            this.GetAsync(query, null);
        }
        
        public void GetAsync(string query, object userState) {
            if ((this.onBeginGetDelegate == null)) {
                this.onBeginGetDelegate = new BeginOperationDelegate(this.OnBeginGet);
            }
            if ((this.onEndGetDelegate == null)) {
                this.onEndGetDelegate = new EndOperationDelegate(this.OnEndGet);
            }
            if ((this.onGetCompletedDelegate == null)) {
                this.onGetCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCompleted);
            }
            base.InvokeAsync(this.onBeginGetDelegate, new object[] {
                        query}, this.onEndGetDelegate, this.onGetCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Money.DBService.DBService.BeginGetSchema(Money.DBService.GetSchemaRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSchema(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetSchema(System.AsyncCallback callback, object asyncState) {
            Money.DBService.GetSchemaRequest inValue = new Money.DBService.GetSchemaRequest();
            inValue.Body = new Money.DBService.GetSchemaRequestBody();
            return ((Money.DBService.DBService)(this)).BeginGetSchema(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Money.DBService.GetSchemaResponse Money.DBService.DBService.EndGetSchema(System.IAsyncResult result) {
            return base.Channel.EndGetSchema(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetSchema(System.IAsyncResult result) {
            Money.DBService.GetSchemaResponse retVal = ((Money.DBService.DBService)(this)).EndGetSchema(result);
            return retVal.Body.GetSchemaResult;
        }
        
        private System.IAsyncResult OnBeginGetSchema(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetSchema(callback, asyncState);
        }
        
        private object[] OnEndGetSchema(System.IAsyncResult result) {
            string retVal = this.EndGetSchema(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSchemaCompleted(object state) {
            if ((this.GetSchemaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSchemaCompleted(this, new GetSchemaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSchemaAsync() {
            this.GetSchemaAsync(null);
        }
        
        public void GetSchemaAsync(object userState) {
            if ((this.onBeginGetSchemaDelegate == null)) {
                this.onBeginGetSchemaDelegate = new BeginOperationDelegate(this.OnBeginGetSchema);
            }
            if ((this.onEndGetSchemaDelegate == null)) {
                this.onEndGetSchemaDelegate = new EndOperationDelegate(this.OnEndGetSchema);
            }
            if ((this.onGetSchemaCompletedDelegate == null)) {
                this.onGetSchemaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSchemaCompleted);
            }
            base.InvokeAsync(this.onBeginGetSchemaDelegate, null, this.onEndGetSchemaDelegate, this.onGetSchemaCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Money.DBService.DBService CreateChannel() {
            return new DBServiceClientChannel(this);
        }
        
        private class DBServiceClientChannel : ChannelBase<Money.DBService.DBService>, Money.DBService.DBService {
            
            public DBServiceClientChannel(System.ServiceModel.ClientBase<Money.DBService.DBService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetDeflate(Money.DBService.GetDeflateRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetDeflate", _args, callback, asyncState);
                return _result;
            }
            
            public Money.DBService.GetDeflateResponse EndGetDeflate(System.IAsyncResult result) {
                object[] _args = new object[0];
                Money.DBService.GetDeflateResponse _result = ((Money.DBService.GetDeflateResponse)(base.EndInvoke("GetDeflate", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetGZip(Money.DBService.GetGZipRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetGZip", _args, callback, asyncState);
                return _result;
            }
            
            public Money.DBService.GetGZipResponse EndGetGZip(System.IAsyncResult result) {
                object[] _args = new object[0];
                Money.DBService.GetGZipResponse _result = ((Money.DBService.GetGZipResponse)(base.EndInvoke("GetGZip", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGet(Money.DBService.GetRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("Get", _args, callback, asyncState);
                return _result;
            }
            
            public Money.DBService.GetResponse EndGet(System.IAsyncResult result) {
                object[] _args = new object[0];
                Money.DBService.GetResponse _result = ((Money.DBService.GetResponse)(base.EndInvoke("Get", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetSchema(Money.DBService.GetSchemaRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetSchema", _args, callback, asyncState);
                return _result;
            }
            
            public Money.DBService.GetSchemaResponse EndGetSchema(System.IAsyncResult result) {
                object[] _args = new object[0];
                Money.DBService.GetSchemaResponse _result = ((Money.DBService.GetSchemaResponse)(base.EndInvoke("GetSchema", _args, result)));
                return _result;
            }
        }
    }
}
