[MSVC Status File]
Version=1.00
ProjectType=10
External=1
DebugBuildCmd=NMAKE /f MAKEFILE
ReleaseBuildCmd=NMAKE /f MAKEFILE
RebuildOption=/a
BuildMode=1
TargetName=D:\DEV\RAYCAST\WT4WIN\wtwin.EXE
BrkptCount=0
WatchCount=0
