/****************************************************************************
 *                   Copyright  1995  INSO Corporation                      *
 *                International CorrectSpell[TM] Software                   *
 *                                                                          *
 * This work is protected by United States and international copyright laws *
 * and contains certain trade secret information.  All use of this work is  *
 * governed by the terms of agreements between INSO Corporation and its     *
 * licensees or potential licensees.  Disclosure or disassembly of the      *
 * contents of embodied programs or algorithms is prohibited.  All rights   *
 * are reserved worldwide.                                                  *
 ****************************************************************************
 
*-----------------------------------------------------------------------*
*                                                                       *
*        ICpmcpre.h -  Specific file for the PowerMac platform of the	*
*							  INSO  Corporation CorrectSpell(TM)               *
*							   Software												      *
*                                                                       *
*-----------------------------------------------------------------------*

* "Predefs" for ICS, as compiled for the Power Macintosh using the
	Metrowerks CodeWarrior compiler. 											  */

#define SF_ICS
#define SL_HMCH2
#define SL_HMCH5
#define SL_HMCH7
