// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "ImageControlWrapper.h"

/////////////////////////////////////////////////////////////////////////////
// CImageControl

IMPLEMENT_DYNCREATE(CImageControl, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CImageControl properties

/////////////////////////////////////////////////////////////////////////////
// CImageControl operations
