/*
 *    WTWIN.H
 */

/* Menu Items */
#define ID_FILE_ABOUT       				102
#define ID_FILE_OPEN        				103
#define ID_FILE_EXIT        				104
#define ID_STUFF_FRAMERATE_RAW_WING    105
#define ID_STUFF_FRAMERATE_RAW_WT      106
#define ID_STUFF_FRAMERATE_STATIC      107
#define ID_STUFF_FRAMERATE_DYNAMIC     108
#define ID_STUFF_STATISTICS				110
#define ID_STUFF_RESET						111
#define ID_STUFF_PLAYER_INFO				112
#define ID_STUFF_SHOW_RENDERING			113

#define ID_STUFF_1X							120
#define ID_STUFF_2X							121

#define MAXFILENAME 256 	     /* maximum length of file pathname      */
#define MAXCUSTFILTER 40	     /* maximum size of custom filter buffer */

//stuff for wtwin.rc, string table.  not used by EXE, only for storing info.
#define IDS_STRING1                     1
#define IDS_STRING2                     2
#define IDS_STRING3                     3
#define IDS_STRING4                     4
