// Source file: mci.cpp
WORD MCIOpenDevice( LPSTR lpDeviceType );
WORD MCIOpen( WORD wDeviceID, LPSTR lpFileName, LPSTR lpAlias, HWND hWndPlay = NULL, long lStartFrame = 0, LPSTR lpDevType = NULL );
BOOL MCIPlay( WORD wDeviceID, HWND hWndNotify = NULL, long lFrom = -1, long lTo = -1, DWORD dwSpeed = 0L, BOOL bFullScreen = NO, BOOL bRepeat = FALSE );
BOOL MCIPause( WORD wDeviceID );
BOOL MCIResume( WORD wDeviceID );
BOOL MCIStop( WORD wDeviceID, BOOL fWait = FALSE );
BOOL MCISetTimeFormat( WORD wDeviceID, DWORD dwFormat );
BOOL MCISetVideoPalette( WORD wDeviceID, HPALETTE hPal );
BOOL MCISetVideoSpeed( WORD wDeviceID, DWORD dwSpeed = 1000L );
BOOL MCISetVideoOnOff( WORD wDeviceID, BOOL bFlag );
BOOL MCISetAudioOnOff( WORD wDeviceID, BOOL bFlag );
BOOL MCISetAudioStream( WORD wDeviceID, DWORD dwStream);
BOOL MCISeek( WORD wDeviceID, long lFrame );
BOOL MCISeekHome( WORD wDeviceID );
BOOL MCISeekEnd( WORD wDeviceID );
BOOL MCIStepForward( WORD wDeviceID, int nFrames );
BOOL MCIStepReverse( WORD wDeviceID );
BOOL MCIUpdate( WORD wDeviceID, HDC hDC );
DWORD MCIGetLength( WORD wDeviceID );
DWORD MCIGetMode( WORD wDeviceID );
DWORD MCIGetPosition( WORD wDeviceID );
BOOL MCIGetSrcRect( WORD wDeviceID, LPRECT lpRect );
BOOL MCIGetDstRect( WORD wDeviceID, LPRECT lpRect );
BOOL MCIClose( WORD wDeviceID );
BOOL MCICloseAll( void );
UINT MCIHandleNotify( HWND hWnd, UINT codeNotify, HMCI hDevice );
void MCILoop( WORD wDeviceID, BOOL bOn, long lFrom = -1, long lTo = -1 );
BOOL MCIIsLooped( WORD wDeviceID, LPLONG lpFrom = NULL, LPLONG lpTo = NULL );
DWORD MCIGetVolume( LPSTR lpDeviceType );
void MCISetVolume( LPSTR lpDeviceType, WORD wVolumeLeft, WORD wVolumeRight );
void MCIError( DWORD dwResult );
int cNumAudio(void);
BOOL OpenPlayCloseVFW( HWND hWndNotify,HWND hWndPlay,LPSTR lpVFWfile);
//void CALLBACK EXPORT MCICallback( HDRVR h, UINT uMessage, DWORD dwUser, DWORD dwParam1, DWORD dwParam2 );
BOOL MCISetDestination( WORD wDeviceID, int x, int y );
BOOL MCIClip( WORD wDeviceID, LPRECT lpSrcClipRect = NULL, LPRECT lpDstClipRect = NULL, int iScale = 1 );
